import { Key } from "react";

export type CountriesData = {
  id: Key;
  country: string;
  cities: string[];
  flag: string;
  capital: string;
  population: number;
  region: string;
  regionshortcut: string;
};

export const countriesData: CountriesData[] = [
  {
    id: 1,
    country: "Afghanistan",
    capital: "Kabul",
    population: 38928346,
    region: "Asia",
    regionshortcut: "AS",
    cities: ["Herat", "Kabul", "Kandahar"],
    flag: "https://flagcdn.com/w320/af.png",
  },
  {
    id: 2,
    country: "Albania",
    capital: "Tirana",
    population: 2877797,
    region: "Europe",
    regionshortcut: "EU",
    cities: ["Elbasan", "Petran", "Pogradec"],
    flag: "https://flagcdn.com/w320/al.png",
  },
  {
    id: 3,
    country: "Algeria",
    capital: "Algiers",
    population: 43851044,
    region: "Africa",
    regionshortcut: "AF",
    cities: ["Algiers", "Oran", "Constantine"],
    flag: "https://flagcdn.com/w320/dz.png",
  },
  {
    id: 4,
    country: "Andorra",
    capital: "Andorra la Vella",
    population: 77265,
    region: "Europe",
    regionshortcut: "EU",
    cities: ["Andorra la Vella", "Escaldes-Engordany", "Encamp"],
    flag: "https://flagcdn.com/w320/ad.png",
  },
  {
    id: 5,
    country: "Angola",
    capital: "Luanda",
    population: 32866272,
    region: "Africa",
    regionshortcut: "AF",
    cities: ["Luanda", "Ndalatando", "Lubango"],
    flag: "https://flagcdn.com/w320/ao.png",
  },
  {
    id: 6,
    country: "Antigua and Barbuda",
    capital: "Saint John's",
    population: 97929,
    region: "North America",
    regionshortcut: "NA",
    cities: ["Saint John's", "All Saints", "Liberta"],
    flag: "https://flagcdn.com/w320/ag.png",
  },
  {
    id: 7,
    country: "Argentina",
    capital: "Buenos Aires",
    population: 45195774,
    region: "South America",
    regionshortcut: "SA",
    cities: ["Buenos Aires", "Cordoba", "Rosario"],
    flag: "https://flagcdn.com/w320/ar.png",
  },
  {
    id: 8,
    country: "Armenia",
    capital: "Yerevan",
    population: 2963243,
    region: "Asia",
    regionshortcut: "AS",
    cities: ["Yerevan", "Gyumri", "Vanadzor"],
    flag: "https://flagcdn.com/w320/am.png",
  },
  {
    id: 9,
    country: "Australia",
    capital: "Canberra",
    population: 25499884,
    region: "Oceania",
    regionshortcut: "OC",
    cities: ["Sydney", "Melbourne", "Brisbane"],
    flag: "https://flagcdn.com/w320/au.png",
  },
  {
    id: 10,
    country: "Austria",
    capital: "Vienna",
    population: 9006398,
    region: "Europe",
    regionshortcut: "EU",
    cities: ["Vienna", "Salzburg", "Graz"],
    flag: "https://flagcdn.com/w320/at.png",
  },
  {
    id: 11,
    country: "Azerbaijan",
    capital: "Baku",
    population: 10139177,
    region: "Asia",
    regionshortcut: "AS",
    cities: ["Baku", "Ganja", "Lankaran"],
    flag: "https://flagcdn.com/w320/az.png",
  },
  {
    id: 12,
    country: "Bahamas",
    capital: "Nassau",
    population: 393248,
    region: "North America",
    regionshortcut: "NA",
    cities: ["Nassau", "Freeport", "West End"],
    flag: "https://flagcdn.com/w320/bs.png",
  },
  {
    id: 13,
    country: "Bahrain",
    capital: "Manama",
    population: 1701583,
    region: "Asia",
    regionshortcut: "AS",
    cities: ["Manama", "Muharraq", "Riffa"],
    flag: "https://flagcdn.com/w320/bh.png",
  },
  {
    id: 14,
    country: "Bangladesh",
    capital: "Dhaka",
    population: 164689383,
    region: "Asia",
    regionshortcut: "AS",
    cities: ["Dhaka", "Chittagong", "Khulna"],
    flag: "https://flagcdn.com/w320/bd.png",
  },
  {
    id: 15,
    country: "Barbados",
    capital: "Bridgetown",
    population: 287371,
    region: "North America",
    regionshortcut: "NA",
    cities: ["Bridgetown", "Oistins", "Speightstown"],
    flag: "https://flagcdn.com/w320/bb.png",
  },
  {
    id: 16,
    country: "Belarus",
    capital: "Minsk",
    population: 9449323,
    region: "Europe",
    regionshortcut: "EU",
    cities: ["Minsk", "Brest", "Gomel"],
    flag: "https://flagcdn.com/w320/by.png",
  },
  {
    id: 17,
    country: "Belgium",
    capital: "Brussels",
    population: 11589623,
    region: "Europe",
    regionshortcut: "EU",
    cities: ["Brussels", "Antwerp", "Ghent"],
    flag: "https://flagcdn.com/w320/be.png",
  },
  {
    id: 18,
    country: "Belize",
    capital: "Belmopan",
    population: 397621,
    region: "North America",
    regionshortcut: "NA",
    cities: ["Belmopan", "Belize City", "San Ignacio"],
    flag: "https://flagcdn.com/w320/bz.png",
  },
  {
    id: 19,
    country: "Benin",
    capital: "Porto-Novo",
    population: 12123200,
    region: "Africa",
    regionshortcut: "AF",
    cities: ["Cotonou", "Porto-Novo", "Parakou"],
    flag: "https://flagcdn.com/w320/bj.png",
  },
  {
    id: 20,
    country: "Bhutan",
    capital: "Thimphu",
    population: 771608,
    region: "Asia",
    regionshortcut: "AS",
    cities: ["Thimphu", "Paro", "Phuentsholing"],
    flag: "https://flagcdn.com/w320/bt.png",
  },
  {
    id: 21,
    country: "Bolivia",
    capital: "Sucre",
    population: 11673021,
    region: "South America",
    regionshortcut: "SA",
    cities: ["La Paz", "Santa Cruz", "Cochabamba"],
    flag: "https://flagcdn.com/w320/bo.png",
  },
  {
    id: 22,
    country: "Bosnia and Herzegovina",
    capital: "Sarajevo",
    population: 3280819,
    region: "Europe",
    regionshortcut: "EU",
    cities: ["Sarajevo", "Banja Luka", "Tuzla"],
    flag: "https://flagcdn.com/w320/ba.png",
  },
  {
    id: 23,
    country: "Botswana",
    capital: "Gaborone",
    population: 2141206,
    region: "Africa",
    regionshortcut: "AF",
    cities: ["Gaborone", "Francistown", "Maun"],
    flag: "https://flagcdn.com/w320/bw.png",
  },
  {
    id: 24,
    country: "Brazil",
    capital: "Brasília",
    population: 211049527,
    region: "South America",
    regionshortcut: "SA",
    cities: ["Brasília", "São Paulo", "Rio de Janeiro"],
    flag: "https://flagcdn.com/w320/br.png",
  },
  {
    id: 25,
    country: "Brunei",
    capital: "Bandar Seri Begawan",
    population: 437479,
    region: "Asia",
    regionshortcut: "AS",
    cities: ["Bandar Seri Begawan", "Kuala Belait", "Seria"],
    flag: "https://flagcdn.com/w320/bn.png",
  },
  {
    id: 26,
    country: "Bulgaria",
    capital: "Sofia",
    population: 6948445,
    region: "Europe",
    regionshortcut: "EU",
    cities: ["Sofia", "Plovdiv", "Varna"],
    flag: "https://flagcdn.com/w320/bg.png",
  },
  {
    id: 27,
    country: "Burkina Faso",
    capital: "Ouagadougou",
    population: 21255918,
    region: "Africa",
    regionshortcut: "AF",
    cities: ["Ouagadougou", "Bobo-Dioulasso", "Koudougou"],
    flag: "https://flagcdn.com/w320/bf.png",
  },
  {
    id: 28,
    country: "Burundi",
    capital: "Gitega",
    population: 10114505,
    region: "Africa",
    regionshortcut: "AF",
    cities: ["Bujumbura", "Gitega", "Ngozi"],
    flag: "https://flagcdn.com/w320/bi.png",
  },
  {
    id: 29,
    country: "Cabo Verde",
    capital: "Praia",
    population: 531239,
    region: "Africa",
    regionshortcut: "AF",
    cities: ["Praia", "Mindelo", "Santa Maria"],
    flag: "https://flagcdn.com/w320/cv.png",
  },
  {
    id: 30,
    country: "Cambodia",
    capital: "Phnom Penh",
    population: 16718971,
    region: "Asia",
    regionshortcut: "AS",
    cities: ["Phnom Penh", "Siem Reap", "Battambang"],
    flag: "https://flagcdn.com/w320/kh.png",
  },
  {
    id: 31,
    country: "Cameroon",
    capital: "Yaoundé",
    population: 22709892,
    region: "Africa",
    regionshortcut: "AF",
    cities: ["Yaoundé", "Douala", "Bafoussam"],
    flag: "https://flagcdn.com/w320/cm.png",
  },
  {
    id: 32,
    country: "Canada",
    capital: "Ottawa",
    population: 37742154,
    region: "North America",
    regionshortcut: "NA",
    cities: ["Ottawa", "Toronto", "Vancouver"],
    flag: "https://flagcdn.com/w320/ca.png",
  },
  {
    id: 33,
    country: "Central African Republic",
    capital: "Bangui",
    population: 4998000,
    region: "Africa",
    regionshortcut: "AF",
    cities: ["Bangui", "Bangassou", "Berberati"],
    flag: "https://flagcdn.com/w320/cf.png",
  },
  {
    id: 34,
    country: "Chad",
    capital: "N'Djamena",
    population: 1449700,
    region: "Africa",
    regionshortcut: "AF",
    cities: ["N'Djamena", "Moundou", "Sarh"],
    flag: "https://flagcdn.com/w320/td.png",
  },
  {
    id: 35,
    country: "Chile",
    capital: "Santiago",
    population: 19116209,
    region: "South America",
    regionshortcut: "SA",
    cities: ["Santiago", "Valparaíso", "Concepción"],
    flag: "https://flagcdn.com/w320/cl.png",
  },
  {
    id: 36,
    country: "China",
    capital: "Beijing",
    population: 1393780000,
    region: "Asia",
    regionshortcut: "AS",
    cities: ["Beijing", "Shanghai", "Guangzhou"],
    flag: "https://flagcdn.com/w320/cn.png",
  },
  {
    id: 37,
    country: "Colombia",
    capital: "Bogotá",
    population: 50882891,
    region: "South America",
    regionshortcut: "SA",
    cities: ["Bogotá", "Medellín", "Cali"],
    flag: "https://flagcdn.com/w320/co.png",
  },
  {
    id: 38,
    country: "Comoros",
    capital: "Moroni",
    population: 806153,
    region: "Africa",
    regionshortcut: "AF",
    cities: ["Moroni", "Mitsamiouli", "Fomboni"],
    flag: "https://flagcdn.com/w320/km.png",
  },
  {
    id: 39,
    country: "Congo, Republic of the",
    capital: "Brazzaville",
    population: 4741000,
    region: "Africa",
    regionshortcut: "AF",
    cities: ["Brazzaville", "Pointe-Noire", "Dolisie"],
    flag: "https://flagcdn.com/w320/cg.png",
  },
  {
    id: 40,
    country: "Congo, Democratic Republic of the",
    capital: "Kinshasa",
    population: 85026000,
    region: "Africa",
    regionshortcut: "AF",
    cities: ["Kinshasa", "Lubumbashi", "Goma"],
    flag: "https://flagcdn.com/w320/cd.png",
  },
  {
    id: 41,
    country: "Costa Rica",
    capital: "San José",
    population: 5094114,
    region: "North America",
    regionshortcut: "NA",
    cities: ["San José", "Alajuela", "Cartago"],
    flag: "https://flagcdn.com/w320/cr.png",
  },
  {
    id: 42,
    country: "Croatia",
    capital: "Zagreb",
    population: 4097365,
    region: "Europe",
    regionshortcut: "EU",
    cities: ["Zagreb", "Split", "Rijeka"],
    flag: "https://flagcdn.com/w320/hr.png",
  },
  {
    id: 43,
    country: "Cuba",
    capital: "Havana",
    population: 11326616,
    region: "North America",
    regionshortcut: "NA",
    cities: ["Havana", "Santiago de Cuba", "Camagüey"],
    flag: "https://flagcdn.com/w320/cu.png",
  },
  {
    id: 44,
    country: "Cyprus",
    capital: "Nicosia",
    population: 1207359,
    region: "Europe",
    regionshortcut: "EU",
    cities: ["Nicosia", "Limassol", "Larnaca"],
    flag: "https://flagcdn.com/w320/cy.png",
  },
  {
    id: 45,
    country: "Czech Republic",
    capital: "Prague",
    population: 10708981,
    region: "Europe",
    regionshortcut: "EU",
    cities: ["Prague", "Brno", "Ostrava"],
    flag: "https://flagcdn.com/w320/cz.png",
  },
  {
    id: 46,
    country: "Denmark",
    capital: "Copenhagen",
    population: 5818553,
    region: "Europe",
    regionshortcut: "EU",
    cities: ["Copenhagen", "Aarhus", "Odense"],
    flag: "https://flagcdn.com/w320/dk.png",
  },
  {
    id: 47,
    country: "Djibouti",
    capital: "Djibouti",
    population: 888000,
    region: "Africa",
    regionshortcut: "AF",
    cities: ["Djibouti", "Ali Sabieh", "Tadjoura"],
    flag: "https://flagcdn.com/w320/dj.png",
  },
  {
    id: 48,
    country: "Dominica",
    capital: "Roseau",
    population: 71808,
    region: "North America",
    regionshortcut: "NA",
    cities: ["Roseau", "Portsmouth", "Marigot"],
    flag: "https://flagcdn.com/w320/dm.png",
  },
  {
    id: 49,
    country: "Dominican Republic",
    capital: "Santo Domingo",
    population: 10738958,
    region: "North America",
    regionshortcut: "NA",
    cities: ["Santo Domingo", "Santiago", "La Romana"],
    flag: "https://flagcdn.com/w320/do.png",
  },
  {
    id: 50,
    country: "Ecuador",
    capital: "Quito",
    population: 17532500,
    region: "South America",
    regionshortcut: "SA",
    cities: ["Quito", "Guayaquil", "Cuenca"],
    flag: "https://flagcdn.com/w320/ec.png",
  },

  {
    id: 51,
    country: "Egypt",
    cities: ["Cairo", "Alexandria", "Giza"],
    flag: "https://flagcdn.com/w320/eg.png",
    capital: "Cairo",
    population: 104124440,
    region: "Africa",
    regionshortcut: "AF",
  },
  {
    id: 52,
    country: "El Salvador",
    cities: ["San Salvador", "Santa Ana", "San Miguel"],
    flag: "https://flagcdn.com/w320/sv.png",
    capital: "San Salvador",
    population: 6486201,
    region: "North America",
    regionshortcut: "NA",
  },
  {
    id: 53,
    country: "Equatorial Guinea",
    cities: ["Malabo", "Bata", "Ebebiyin"],
    flag: "https://flagcdn.com/w320/gq.png",
    capital: "Malabo",
    population: 1402985,
    region: "Africa",
    regionshortcut: "AF",
  },
  {
    id: 54,
    country: "Eritrea",
    cities: ["Asmara", "Keren", "Mendefera"],
    flag: "https://flagcdn.com/w320/er.png",
    capital: "Asmara",
    population: 3546064,
    region: "Africa",
    regionshortcut: "AF",
  },
  {
    id: 55,
    country: "Estonia",
    cities: ["Tallinn", "Tartu", "Narva"],
    flag: "https://flagcdn.com/w320/ee.png",
    capital: "Tallinn",
    population: 1326535,
    region: "Europe",
    regionshortcut: "EU",
  },
  {
    id: 56,
    country: "Eswatini",
    cities: ["Mbabane", "Manzini", "Lobamba"],
    flag: "https://flagcdn.com/w320/sz.png",
    capital: "Mbabane",
    population: 1160164,
    region: "Africa",
    regionshortcut: "AF",
  },
  {
    id: 57,
    country: "Ethiopia",
    cities: ["Addis Ababa", "Gondar", "Adama"],
    flag: "https://flagcdn.com/w320/et.png",
    capital: "Addis Ababa",
    population: 126527000,
    region: "Africa",
    regionshortcut: "AF",
  },
  {
    id: 58,
    country: "Fiji",
    cities: ["Suva", "Nadi", "Lautoka"],
    flag: "https://flagcdn.com/w320/fj.png",
    capital: "Suva",
    population: 896444,
    region: "Oceania",
    regionshortcut: "OC",
  },
  {
    id: 59,
    country: "Finland",
    cities: ["Helsinki", "Espoo", "Tampere"],
    flag: "https://flagcdn.com/w320/fi.png",
    capital: "Helsinki",
    population: 5540720,
    region: "Europe",
    regionshortcut: "EU",
  },
  {
    id: 60,
    country: "France",
    cities: ["Paris", "Marseille", "Lyon"],
    flag: "https://flagcdn.com/w320/fr.png",
    capital: "Paris",
    population: 67391582,
    region: "Europe",
    regionshortcut: "EU",
  },
  {
    id: 61,
    country: "Gabon",
    cities: ["Libreville", "Port-Gentil", "Franceville"],
    flag: "https://flagcdn.com/w320/ga.png",
    capital: "Libreville",
    population: 2110271,
    region: "Africa",
    regionshortcut: "AF",
  },
  {
    id: 62,
    country: "Gambia",
    cities: ["Banjul", "Serrekunda", "Brikama"],
    flag: "https://flagcdn.com/w320/gm.png",
    capital: "Banjul",
    population: 2416668,
    region: "Africa",
    regionshortcut: "AF",
  },
  {
    id: 63,
    country: "Georgia",
    cities: ["Tbilisi", "Batumi", "Zugdidi"],
    flag: "https://flagcdn.com/w320/ge.png",
    capital: "Tbilisi",
    population: 3989167,
    region: "Asia",
    regionshortcut: "AS",
  },
  {
    id: 64,
    country: "Germany",
    cities: ["Berlin", "Munich", "Hamburg"],
    flag: "https://flagcdn.com/w320/de.png",
    capital: "Berlin",
    population: 83166711,
    region: "Europe",
    regionshortcut: "EU",
  },
  {
    id: 65,
    country: "Ghana",
    cities: ["Accra", "Kumasi", "Takoradi"],
    flag: "https://flagcdn.com/w320/gh.png",
    capital: "Accra",
    population: 31207000,
    region: "Africa",
    regionshortcut: "AF",
  },
  {
    id: 66,
    country: "Greece",
    cities: ["Athens", "Thessaloniki", "Patras"],
    flag: "https://flagcdn.com/w320/gr.png",
    capital: "Athens",
    population: 10755000,
    region: "Europe",
    regionshortcut: "EU",
  },
  {
    id: 67,
    country: "Grenada",
    cities: ["St. George's", "Grenville", "Gouyave"],
    flag: "https://flagcdn.com/w320/gd.png",
    capital: "St. George's",
    population: 112523,
    region: "North America",
    regionshortcut: "NA",
  },
  {
    id: 68,
    country: "Guatemala",
    cities: ["Guatemala City", "Mixco", "Villa Nueva"],
    flag: "https://flagcdn.com/w320/gt.png",
    capital: "Guatemala City",
    population: 17915568,
    region: "North America",
    regionshortcut: "NA",
  },
  {
    id: 69,
    country: "Guinea",
    cities: ["Conakry", "Kankan", "Nzérékoré"],
    flag: "https://flagcdn.com/w320/gn.png",
    capital: "Conakry",
    population: 13209100,
    region: "Africa",
    regionshortcut: "AF",
  },
  {
    id: 70,
    country: "Guinea-Bissau",
    cities: ["Bissau", "Bafata", "Gabu"],
    flag: "https://flagcdn.com/w320/gw.png",
    capital: "Bissau",
    population: 2020000,
    region: "Africa",
    regionshortcut: "AF",
  },
  {
    id: 71,
    country: "Guyana",
    cities: ["Georgetown", "New Amsterdam", "Linden"],
    flag: "https://flagcdn.com/w320/gy.png",
    capital: "Georgetown",
    population: 790326,
    region: "South America",
    regionshortcut: "SA",
  },
  {
    id: 72,
    country: "Haiti",
    cities: ["Port-au-Prince", "Cap-Haïtien", "Jacmel"],
    flag: "https://flagcdn.com/w320/ht.png",
    capital: "Port-au-Prince",
    population: 11078033,
    region: "North America",
    regionshortcut: "NA",
  },
  {
    id: 73,
    country: "Honduras",
    cities: ["Tegucigalpa", "San Pedro Sula", "Choluteca"],
    flag: "https://flagcdn.com/w320/hn.png",
    capital: "Tegucigalpa",
    population: 9875000,
    region: "North America",
    regionshortcut: "NA",
  },
  {
    id: 74,
    country: "Hungary",
    cities: ["Budapest", "Debrecen", "Szeged"],
    flag: "https://flagcdn.com/w320/hu.png",
    capital: "Budapest",
    population: 9660351,
    region: "Europe",
    regionshortcut: "EU",
  },

  {
    id: 75,
    country: "Iceland",
    cities: ["Reykjavík", "Akureyri", "Kopavogur"],
    flag: "https://flagcdn.com/w320/is.png",
    capital: "Reykjavík",
    population: 364000,
    region: "Europe",
    regionshortcut: "EU",
  },
  {
    id: 76,
    country: "India",
    cities: ["New Delhi", "Mumbai", "Bengaluru"],
    flag: "https://flagcdn.com/w320/in.png",
    capital: "New Delhi",
    population: 1380004385,
    region: "Asia",
    regionshortcut: "AS",
  },
  {
    id: 77,
    country: "Indonesia",
    cities: ["Jakarta", "Surabaya", "Bandung"],
    flag: "https://flagcdn.com/w320/id.png",
    capital: "Jakarta",
    population: 273523615,
    region: "Asia",
    regionshortcut: "AS",
  },
  {
    id: 78,
    country: "Iran",
    cities: ["Tehran", "Isfahan", "Shiraz"],
    flag: "https://flagcdn.com/w320/ir.png",
    capital: "Tehran",
    population: 83992953,
    region: "Asia",
    regionshortcut: "AS",
  },
  {
    id: 79,
    country: "Iraq",
    cities: ["Baghdad", "Basra", "Erbil"],
    flag: "https://flagcdn.com/w320/iq.png",
    capital: "Baghdad",
    population: 40222503,
    region: "Asia",
    regionshortcut: "AS",
  },
  {
    id: 80,
    country: "Ireland",
    cities: ["Dublin", "Cork", "Limerick"],
    flag: "https://flagcdn.com/w320/ie.png",
    capital: "Dublin",
    population: 4937786,
    region: "Europe",
    regionshortcut: "EU",
  },
  {
    id: 81,
    country: "Israel",
    cities: ["Jerusalem", "Tel Aviv", "Haifa"],
    flag: "https://flagcdn.com/w320/il.png",
    capital: "Jerusalem",
    population: 9000000,
    region: "Asia",
    regionshortcut: "AS",
  },
  {
    id: 82,
    country: "Italy",
    cities: ["Rome", "Milan", "Florence"],
    flag: "https://flagcdn.com/w320/it.png",
    capital: "Rome",
    population: 60262770,
    region: "Europe",
    regionshortcut: "EU",
  },
  {
    id: 83,
    country: "Jamaica",
    cities: ["Kingston", "Montego Bay", "Spanish Town"],
    flag: "https://flagcdn.com/w320/jm.png",
    capital: "Kingston",
    population: 2961167,
    region: "North America",
    regionshortcut: "NA",
  },
  {
    id: 84,
    country: "Japan",
    cities: ["Tokyo", "Osaka", "Kyoto"],
    flag: "https://flagcdn.com/w320/jp.png",
    capital: "Tokyo",
    population: 125584838,
    region: "Asia",
    regionshortcut: "AS",
  },
  {
    id: 85,
    country: "Jordan",
    cities: ["Amman", "Zarqa", "Irbid"],
    flag: "https://flagcdn.com/w320/jo.png",
    capital: "Amman",
    population: 10203140,
    region: "Asia",
    regionshortcut: "AS",
  },
  {
    id: 86,
    country: "Kazakhstan",
    cities: ["Almaty", "Nur-Sultan", "Shymkent"],
    flag: "https://flagcdn.com/w320/kz.png",
    capital: "Nur-Sultan",
    population: 18776707,
    region: "Asia",
    regionshortcut: "AS",
  },
  {
    id: 87,
    country: "Kenya",
    cities: ["Nairobi", "Mombasa", "Kisumu"],
    flag: "https://flagcdn.com/w320/ke.png",
    capital: "Nairobi",
    population: 53771296,
    region: "Africa",
    regionshortcut: "AF",
  },
  {
    id: 88,
    country: "Kiribati",
    cities: ["Tarawa", "Kiritimati", "Banaba"],
    flag: "https://flagcdn.com/w320/ki.png",
    capital: "Tarawa",
    population: 119446,
    region: "Oceania",
    regionshortcut: "OC",
  },
  {
    id: 89,
    country: "Kuwait",
    cities: ["Kuwait City", "Jahra", "Ahmadi"],
    flag: "https://flagcdn.com/w320/kw.png",
    capital: "Kuwait City",
    population: 4420110,
    region: "Asia",
    regionshortcut: "AS",
  },
  {
    id: 90,
    country: "Kyrgyzstan",
    cities: ["Bishkek", "Osh", "Jalal-Abad"],
    flag: "https://flagcdn.com/w320/kg.png",
    capital: "Bishkek",
    population: 6524195,
    region: "Asia",
    regionshortcut: "AS",
  },
  {
    id: 91,
    country: "Laos",
    cities: ["Vientiane", "Luang Prabang", "Pakse"],
    flag: "https://flagcdn.com/w320/la.png",
    capital: "Vientiane",
    population: 7275560,
    region: "Asia",
    regionshortcut: "AS",
  },
  {
    id: 92,
    country: "Latvia",
    cities: ["Riga", "Daugavpils", "Liepaja"],
    flag: "https://flagcdn.com/w320/lv.png",
    capital: "Riga",
    population: 1886198,
    region: "Europe",
    regionshortcut: "EU",
  },
  {
    id: 93,
    country: "Lebanon",
    cities: ["Beirut", "Tripoli", "Sidon"],
    flag: "https://flagcdn.com/w320/lb.png",
    capital: "Beirut",
    population: 6825445,
    region: "Asia",
    regionshortcut: "AS",
  },
  {
    id: 94,
    country: "Lesotho",
    cities: ["Maseru", "Maputsoe", "Teyateyaneng"],
    flag: "https://flagcdn.com/w320/ls.png",
    capital: "Maseru",
    population: 2141200,
    region: "Africa",
    regionshortcut: "AF",
  },
  {
    id: 95,
    country: "Liberia",
    cities: ["Monrovia", "Gbarnga", "Buchanan"],
    flag: "https://flagcdn.com/w320/lr.png",
    capital: "Monrovia",
    population: 5057681,
    region: "Africa",
    regionshortcut: "AF",
  },
  {
    id: 96,
    country: "Libya",
    cities: ["Tripoli", "Benghazi", "Misrata"],
    flag: "https://flagcdn.com/w320/ly.png",
    capital: "Tripoli",
    population: 6871297,
    region: "Africa",
    regionshortcut: "AF",
  },
  {
    id: 97,
    country: "Liechtenstein",
    cities: ["Vaduz", "Schaan", "Eschen"],
    flag: "https://flagcdn.com/w320/li.png",
    capital: "Vaduz",
    population: 38128,
    region: "Europe",
    regionshortcut: "EU",
  },
  {
    id: 98,
    country: "Lithuania",
    cities: ["Vilnius", "Kaunas", "Klaipeda"],
    flag: "https://flagcdn.com/w320/lt.png",
    capital: "Vilnius",
    population: 2722289,
    region: "Europe",
    regionshortcut: "EU",
  },
  {
    id: 99,
    country: "Luxembourg",
    cities: ["Luxembourg City", "Esch-sur-Alzette", "Differdange"],
    flag: "https://flagcdn.com/w320/lu.png",
    capital: "Luxembourg City",
    population: 634814,
    region: "Europe",
    regionshortcut: "EU",
  },
  {
    id: 100,
    country: "Madagascar",
    cities: ["Antananarivo", "Toamasina", "Antsiranana"],
    flag: "https://flagcdn.com/w320/mg.png",
    capital: "Antananarivo",
    population: 27691018,
    region: "Africa",
    regionshortcut: "AF",
  },
  {
    id: 101,
    country: "Malawi",
    cities: ["Lilongwe", "Blantyre", "Mzuzu"],
    flag: "https://flagcdn.com/w320/mw.png",
    capital: "Lilongwe",
    population: 19129952,
    region: "Africa",
    regionshortcut: "AF",
  },
  {
    id: 102,
    country: "Malaysia",
    cities: ["Kuala Lumpur", "George Town", "Malacca"],
    flag: "https://flagcdn.com/w320/my.png",
    capital: "Kuala Lumpur",
    population: 32365999,
    region: "Asia",
    regionshortcut: "AS",
  },
  {
    id: 103,
    country: "Maldives",
    cities: ["Malé", "Fuvahmulah", "Dhidhdhoo"],
    flag: "https://flagcdn.com/w320/mv.png",
    capital: "Malé",
    population: 540544,
    region: "Asia",
    regionshortcut: "AS",
  },
  {
    id: 104,
    country: "Mali",
    cities: ["Bamako", "Sikasso", "Kayes"],
    flag: "https://flagcdn.com/w320/ml.png",
    capital: "Bamako",
    population: 20250833,
    region: "Africa",
    regionshortcut: "AF",
  },
  {
    id: 105,
    country: "Malta",
    cities: ["Valletta", "Sliema", "Birkirkara"],
    flag: "https://flagcdn.com/w320/mt.png",
    capital: "Valletta",
    population: 514064,
    region: "Europe",
    regionshortcut: "EU",
  },
  {
    id: 106,
    country: "Marshall Islands",
    cities: ["Majuro", "Ebeye", "Arno"],
    flag: "https://flagcdn.com/w320/mh.png",
    capital: "Majuro",
    population: 59194,
    region: "Oceania",
    regionshortcut: "OC",
  },
  {
    id: 107,
    country: "Mauritania",
    cities: ["Nouakchott", "Nouadhibou", "Kiffa"],
    flag: "https://flagcdn.com/w320/mr.png",
    capital: "Nouakchott",
    population: 4649658,
    region: "Africa",
    regionshortcut: "AF",
  },
  {
    id: 108,
    country: "Mauritius",
    cities: ["Port Louis", "Curepipe", "Quatre Bornes"],
    flag: "https://flagcdn.com/w320/mu.png",
    capital: "Port Louis",
    population: 1265737,
    region: "Africa",
    regionshortcut: "AF",
  },
  {
    id: 109,
    country: "Mexico",
    cities: ["Mexico City", "Guadalajara", "Monterrey"],
    flag: "https://flagcdn.com/w320/mx.png",
    capital: "Mexico City",
    population: 128933000,
    region: "North America",
    regionshortcut: "NA",
  },
  {
    id: 110,
    country: "Micronesia",
    cities: ["Palikir", "Kolonia", "Yap"],
    flag: "https://flagcdn.com/w320/fm.png",
    capital: "Palikir",
    population: 115023,
    region: "Oceania",
    regionshortcut: "OC",
  },
  {
    id: 111,
    country: "Moldova",
    cities: ["Chisinau", "Bălți", "Bender"],
    flag: "https://flagcdn.com/w320/md.png",
    capital: "Chisinau",
    population: 2657637,
    region: "Europe",
    regionshortcut: "EU",
  },
  {
    id: 112,
    country: "Monaco",
    cities: ["Monaco", "Monte Carlo", "La Condamine"],
    flag: "https://flagcdn.com/w320/mc.png",
    capital: "Monaco",
    population: 39242,
    region: "Europe",
    regionshortcut: "EU",
  },
  {
    id: 113,
    country: "Mongolia",
    cities: ["Ulaanbaatar", "Erdenet", "Darkhan"],
    flag: "https://flagcdn.com/w320/mn.png",
    capital: "Ulaanbaatar",
    population: 3278290,
    region: "Asia",
    regionshortcut: "AS",
  },
  {
    id: 114,
    country: "Montenegro",
    cities: ["Podgorica", "Nikšić", "Herceg Novi"],
    flag: "https://flagcdn.com/w320/me.png",
    capital: "Podgorica",
    population: 622359,
    region: "Europe",
    regionshortcut: "EU",
  },
  {
    id: 115,
    country: "Morocco",
    cities: ["Rabat", "Casablanca", "Marrakech"],
    flag: "https://flagcdn.com/w320/ma.png",
    capital: "Rabat",
    population: 36910560,
    region: "Africa",
    regionshortcut: "AF",
  },
  {
    id: 116,
    country: "Mozambique",
    cities: ["Maputo", "Beira", "Nampula"],
    flag: "https://flagcdn.com/w320/mz.png",
    capital: "Maputo",
    population: 31255435,
    region: "Africa",
    regionshortcut: "AF",
  },
  {
    id: 117,
    country: "Myanmar",
    cities: ["Naypyidaw", "Yangon", "Mandalay"],
    flag: "https://flagcdn.com/w320/mm.png",
    capital: "Naypyidaw",
    population: 53800000,
    region: "Asia",
    regionshortcut: "AS",
  },
  {
    id: 118,
    country: "Namibia",
    cities: ["Windhoek", "Swakopmund", "Rundu"],
    flag: "https://flagcdn.com/w320/na.png",
    capital: "Windhoek",
    population: 2540905,
    region: "Africa",
    regionshortcut: "AF",
  },
  {
    id: 119,
    country: "Nauru",
    cities: ["Yaren", "Aiwo", "Boe"],
    flag: "https://flagcdn.com/w320/nr.png",
    capital: "Yaren",
    population: 10084,
    region: "Oceania",
    regionshortcut: "OC",
  },
  {
    id: 120,
    country: "Nepal",
    cities: ["Kathmandu", "Pokhara", "Biratnagar"],
    flag: "https://flagcdn.com/w320/np.png",
    capital: "Kathmandu",
    population: 29136808,
    region: "Asia",
    regionshortcut: "AS",
  },
  {
    id: 121,
    country: "Netherlands",
    cities: ["Amsterdam", "Rotterdam", "Utrecht"],
    flag: "https://flagcdn.com/w320/nl.png",
    capital: "Amsterdam",
    population: 17134872,
    region: "Europe",
    regionshortcut: "EU",
  },
  {
    id: 122,
    country: "New Zealand",
    cities: ["Wellington", "Auckland", "Christchurch"],
    flag: "https://flagcdn.com/w320/nz.png",
    capital: "Wellington",
    population: 5084300,
    region: "Oceania",
    regionshortcut: "OC",
  },
  {
    id: 123,
    country: "Nicaragua",
    cities: ["Managua", "León", "Granada"],
    flag: "https://flagcdn.com/w320/ni.png",
    capital: "Managua",
    population: 6461000,
    region: "Americas",
    regionshortcut: "NA",
  },
];
