import {Key} from "react";

export type CountriesData = {
  id: Key;
  country: string;
  cities: string[];
};

export const countriesData: CountriesData[] = [
  {
    id: 1,
    country: "Afghanistan",
    cities: [
      "Herat",
      "Kabul",
      "Kandahar",
      "Molah",
      "Rana",
      "Shar",
      "Sharif",
      "Wazir Akbar Khan",
    ],
  },
  {
    id: 2,
    country: "Albania",
    cities: [
      "Elbasan",
      "Petran",
      "Pogradec",
      "Shkoder",
      "Tirana",
      "Ura Vajgurore",
    ],
  },
  {
    id: 3,
    country: "Algeria",
    cities: [
      "Algiers",
      "Annaba",
      "Azazga",
      "Batna City",
      "Blida",
      "Bordj",
      "Bordj Bou Arreridj",
      "Bougara",
      "Cheraga",
      "Chlef",
      "Constantine",
      "Djelfa",
      "Draria",
      "El Tarf",
      "Hussein Dey",
      "Illizi",
      "Jijel",
      "Kouba",
      "Laghouat",
      "Oran",
      "Ouargla",
      "Oued Smar",
      "Relizane",
      "Rouiba",
      "Saida",
      "Souk Ahras",
      "Tamanghasset",
      "Tiaret",
      "Tissemsilt",
      "Tizi",
      "Tizi Ouzou",
      "Tlemcen",
    ],
  },
  {
    id: 4,
    country: "Andorra",
    cities: [
      "Andorra la Vella",
      "Canillo",
      "Encamp",
      "Engordany",
      "Escaldes-Engordany",
      "La Massana",
      "Llorts",
      "Ordino",
      "Santa Coloma",
      "Sispony",
      "Soldeu",
    ],
  },
  {
    id: 5,
    country: "Angola",
    cities: [
      "Ambriz",
      "Benguela",
      "Cabinda",
      "Cacole",
      "Camabatela",
      "Cazeta",
      "Huambo",
      "Kuito",
      "Lobito",
      "Luanda",
      "Lubango",
      "Lucapa",
      "Lumeje",
      "Malanje",
      "Menongue",
      "Muxaluando",
      "Namibe",
      "Ondjiva",
      "Piri",
      "Saurimo",
      "Talatona",
    ],
  },
  {
    id: 6,
    country: "Antigua and Barbuda",
    cities: [
      "All Saints",
      "Cassada Gardens",
      "Codrington",
      "Old Road",
      "Parham",
      "Woods",
    ],
  },
  {
    id: 7,
    country: "Argentina",
    cities: [
      "28 de Noviembre",
      "Abasto",
      "Acassuso",
      "Acebal",
      "Acevedo",
      "Adelia Maria",
      "Agua de Oro",
      "Albardon",
      "Albarellos",
      "Alberdi",
      "Alberti",
      "Aldo Bonzi",
      "Alejandro Korn",
      "Alicia",
      "Allen",
      "Almafuerte",
      "Almagro",
      "Almirante Brown",
      "Alta Gracia",
      "Alta Italia",
      "Alvarez",
      "Alvear",
      "Anatuya",
      "Angelica",
      "Antonio Carboni",
      "Apostoles",
      "Arequito",
      "Armstrong",
      "Arrecifes",
      "Arroyito",
      "Arroyito",
      "Arroyito Challaco",
      "Arroyo Seco",
      "Arteaga",
      "Asamblea",
      "Ascension",
      "Avellaneda",
      "Avellaneda",
      "Ayacucho",
      "Azara",
      "Azul",
      "Balcarce",
      "Balnearia",
      "Banda del Rio Sali",
      "Bandera",
      "Banfield",
      "Baradero",
      "Bariloche",
      "Barrio Fisherton",
      "Batan",
      "Beccar",
      "Belen de Escobar",
      "Belgrano",
      "Belgrano",
      "Bell Ville",
      "Bella Vista",
      "Bella Vista",
      "Benavidez",
      "Berazategui",
      "Berisso",
      "Bernal",
      "Bernardo Larroude",
      "Bernasconi",
      "Bigand",
      "Bombal",
      "Bordenave",
      "Bosch",
      "Bosques",
      "Boulogne",
      "Bovril",
      "Bragado",
      "Brandsen",
      "Brinkmann",
      "Buenos Aires",
      "Burzaco",
      "Bustinza",
      "Caballito",
      "Calderon",
      "Caleta Olivia",
      "Caleufu",
      "Camilo Aldao",
      "Campana",
      "Canada de Gomez",
      "Canada del Ucle",
      "Canada Rosquin",
      "Canals",
      "Canning",
      "Canuelas",
      "Capilla del Monte",
      "Capilla del Senor",
      "Capitan Bermudez",
      "Carhue",
      "Carlos Casares",
      "Carlos Pellegrini",
      "Carlos Tejedor",
      "Caseros",
      "Casilda",
      "Castelar",
      "Castelli",
      "Castillo",
    ],
  },
  {
    id: 8,
    country: "Armenia",
    cities: ["Erewan", "Wanadzor", "Kapan", "Asztarak"],
  },
  {
    id: 9,
    country: "Aruba",
    cities: [
      "Noord",
      "Oranjestad",
      "Palm Beach",
      "Paradera",
      "Ponton",
      "Sabaneta",
      "San Barbola",
      "Santa Cruz",
      "Sero Blanco",
      "Sint Nicolaas",
      "Tanki Lender",
    ],
  },
  {
    id: 10,
    country: "Australia",
    cities: [
      "Abbotsford",
      "Abbotsford",
      "Abbotsham",
      "Aberdeen",
      "Aberfoyle",
      "Aberglasslyn",
      "Abermain",
      "Acacia Ridge",
      "Adamstown",
      "Adelaide",
      "Adelong",
      "Advancetown",
      "Agnes Banks",
      "Agnes Water",
      "Airlie Beach",
      "Aitkenvale",
      "Albany",
      "Albany Creek",
      "Albert Park",
      "Alberton",
      "Alberton",
      "Albion",
      "Albion Park",
      "Albury",
      "Aldgate",
      "Aldinga",
      "Aldinga Beach",
      "Alexandra",
      "Alexandra",
      "Alexandria",
      "Alfredton",
      "Alice Springs",
      "Allambee",
      "Allansford",
      "Allanson",
      "Allora",
      "Alma",
      "Alphington",
      "Alpine",
      "Alstonville",
      "Alton Downs",
      "Altona",
      "Amamoor",
      "Amaroo",
      "Angaston",
      "Anglesea",
      "Anna Bay",
      "Annandale",
      "Apollo Bay",
      "Applecross",
      "Applethorpe",
      "Ararat",
      "Arcadia",
      "Argents Hill",
      "Armadale",
      "Armadale",
      "Armidale",
      "Armstrong Creek",
      "Arno Bay",
      "Arrawarra",
      "Artarmon",
      "Ascot",
      "Ascot Vale",
      "Ashburton",
      "Ashfield",
      "Ashgrove",
      "Ashton",
      "Aspendale",
      "Aspley",
      "Asquith",
      "Atherton",
      "Attadale",
      "Auburn",
      "Augusta",
      "Austinmer",
      "Austins Ferry",
      "Australind",
      "Avalon",
      "Avenue",
      "Avoca Beach",
      "Avondale",
      "Axedale",
      "Aylmerton",
      "Ayr",
      "Babinda",
      "Bacchus Marsh",
      "Bagdad",
      "Bahrs Scrub",
      "Bairnsdale",
      "Baker",
      "Balaclava",
      "Balaklava",
      "Bald Hills",
      "Balgowlah",
      "Balgownie",
      "Balhannah",
      "Ballan",
      "Ballarat",
      "Ballina",
      "Balmain",
    ],
  },
  {
    id: 11,
    country: "Austria",
    cities: [
      "Absam",
      "Absdorf",
      "Abtenau",
      "Abtsdorf",
      "Ach",
      "Achenkirch",
      "Achensee",
      "Admont",
      "Adnet",
      "Afritz",
      "Aggsbach",
      "Aichbach",
      "Aichdorf",
      "Aifersdorf",
      "Aigen",
      "Aigen im Muehlkreis",
      "Ainet",
      "Aistersheim",
      "Alberndorf in der Riedmark",
      "Alberschwende",
      "Aldrans",
      "Alkoven",
      "Alland",
      "Allhartsberg",
      "Alpbach",
      "Altach",
      "Altenberg",
      "Altenberg bei Linz",
      "Altenburg",
      "Altendorf",
      "Altendorf",
      "Altenhof am Hausruck",
      "Altenmarkt an der Triesting",
      "Altenmarkt im Pongau",
      "Altheim",
      "Althofen",
      "Altlengbach",
      "Altlichtenwarth",
      "Altmunster",
      "Altwaidhofen",
      "Am See",
      "Amaliendorf",
      "Ampass",
      "Ampfelwang",
      "Amstetten",
      "Andorf",
      "Anger",
      "Anif",
      "Annenheim",
      "Ansfelden",
      "Anthering",
      "Apfelberg",
      "Arbesthal",
      "Ardagger Markt",
      "Ardning",
      "Arnoldstein",
      "Arriach",
      "Asberg",
      "Aschach an der Donau",
      "Aschau",
      "Aspang Markt",
      "Asparn",
      "Asperhofen",
      "Asten",
      "Attersee",
      "Attnang-Puchheim",
      "Atzbach",
      "Au",
      "Auersthal",
      "Aufhausen",
      "Augsdorf",
      "Aurolzmunster",
      "Axams",
      "Bach",
      "Bad Blumau",
      "Bad Deutsch-Altenburg",
      "Bad Erlach",
      "Bad Fischau",
      "Bad Gams",
      "Bad Gastein",
      "Bad Gleichenberg",
      "Bad Goisern",
      "Bad Hall",
      "Bad Hofgastein",
      "Bad Ischl",
      "Bad Kreuzen",
      "Bad Pirawarth",
      "Bad Radkersburg",
      "Bad Schallerbach",
      "Bad Tatzmannsdorf",
      "Bad Voslau",
      "Baden bei Wien",
      "Baernbach",
      "Baldramsdorf",
      "Bartholomaberg",
      "Barwies",
      "Bauer",
      "Baumgarten im Burgenland",
      "Baumgartenberg",
      "Baumkirchen",
    ],
  },
  {
    id: 12,
    country: "Azerbaijan",
    cities: [
      "Baku",
      "Nakhchivan",
      "Quba",
      "Qusar",
      "Sulutapa",
      "Sumqayit",
      "Xirdalan",
      "Zurges",
    ],
  },
  {
    id: 13,
    country: "Bahamas",
    cities: [
      "Andros Town",
      "Dunmore Town",
      "Freeport",
      "Marsh Harbour",
      "Nassau",
      "Palmetto Point",
      "Spanish Wells",
    ],
  },
  {
    id: 14,
    country: "Bahrain",
    cities: [
      "Al Budayyi`",
      "Al Hadd",
      "Al Hamalah",
      "Al Janabiyah",
      "Al Markh",
      "Al Muharraq",
      "Bani Jamrah",
      "Barbar",
      "Jurdab",
      "Madinat `Isa",
      "Madinat Hamad",
      "Manama",
      "Oil City",
      "Sanabis",
      "Sanad",
      "Sitrah",
      "Tubli",
    ],
  },
  {
    id: 15,
    country: "Bangladesh",
    cities: [
      "Agrabad",
      "Bangla",
      "Barisal",
      "Bazar",
      "Chittagong",
      "Comilla",
      "Delta",
      "Dhaka",
      "Hossain",
      "Jessore",
      "Kabi",
      "Kazipur",
      "Mymensingh",
      "Narayanganj",
      "Rajshahi",
      "Tejgaon",
      "Uttara",
    ],
  },
  {
    id: 16,
    country: "Barbados",
    cities: [
      "Atlantic Shores",
      "Bagatelle",
      "Bloomsbury",
      "Bridgetown",
      "Bruce Vale",
      "Cave Hill",
      "Clapham",
      "Hastings",
      "Holetown",
      "Husbands",
      "Jackmans",
      "Oistins",
      "Pine Housing Estate",
      "Porters",
      "Rendezvous",
      "Rockley",
      "The Garden",
      "Wanstead",
      "Warners",
      "Warrens",
      "White Hill",
      "Wildey",
      "Worthing",
    ],
  },
  {
    id: 17,
    country: "Belarus",
    cities: [
      "Baranovichi",
      "Borisov",
      "Brest",
      "Dzyarzhynsk",
      "Horki",
      "Hrodna",
      "Lahoysk",
      "Lida",
      "Lyakhovichi",
      "Lyaskavichy",
      "Mazyr",
      "Minsk",
      "Mogilev",
      "Navapolatsk",
      "Orsha",
      "Pinsk",
      "Polatsk",
      "Radoshkovichi",
      "Shklow",
      "Vitebsk",
      "Zaslawye",
      "Zhodzina",
    ],
  },
  {
    id: 18,
    country: "Belgium",
    cities: [
      "Aalbeke",
      "Aalst",
      "Aalter",
      "Aarschot",
      "Aarsele",
      "Aartrijke",
      "Aartselaar",
      "Achel",
      "Adegem",
      "Adinkerke",
      "Afsnee",
      "Agimont",
      "Alken",
      "Alleur",
      "Alsemberg",
      "Alveringem",
      "Amay",
      "Ampsin",
      "Andenne",
      "Anderlecht",
      "Anderlues",
      "Andrimont",
      "Angleur",
      "Ans",
      "Anseroeul",
      "Anthisnes",
      "Antwerp",
      "Anzegem",
      "Appels",
      "Appelterre-Eichem",
      "Arbrefontaine",
      "Ardooie",
      "Arendonk",
      "Argenteau",
      "Arlon",
      "Arquennes",
      "Arsimont",
      "As",
      "Asse",
      "Assebroek",
      "Assenede",
      "Assent",
      "Assesse",
      "Astene",
      "Astenet",
      "Ath",
      "Attenhoven",
      "Attre",
      "Aubange",
      "Aubel",
      "Auderghem",
      "Auvelais",
      "Avekapelle",
      "Avelgem",
      "Averbode",
      "Awans",
      "Awirs",
      "Aywaille",
      "Baal",
      "Baarle-Hertog",
      "Baasrode",
      "Baelen",
      "Baisy-Thy",
      "Balen",
      "Banneux",
      "Barchon",
      "Barry",
      "Basecles",
      "Bassenge",
      "Bassevelde",
      "Bastogne",
      "Battice",
      "Baudour",
      "Bavegem",
      "Bavikhove",
      "Bazel",
      "Beaufays",
      "Beauvechain",
      "Beernem",
      "Beerse",
      "Beersel",
      "Beervelde",
      "Beerzel",
      "Beez",
      "Begijnendijk",
      "Beigem",
      "Bekkevoort",
      "Belgrade",
      "Belle Fontaine",
      "Bellem",
      "Beloeil",
      "Belsele",
      "Berchem",
      "Berchem",
      "Berendrecht",
      "Beringen",
      "Berlaar",
      "Berlare",
      "Bernissart",
      "Bertem",
    ],
  },
  {
    id: 19,
    country: "Belize",
    cities: [
      "Belize City",
      "Belmopan",
      "Benque Viejo del Carmen",
      "Freetown Sibun",
      "Ladyville",
      "San Ignacio",
      "San Pedro Town",
    ],
  },
  {
    id: 20,
    country: "Bolivia",
    cities: [
      "Anillo",
      "Aroma",
      "Bermejo",
      "Caracasa",
      "Cobija",
      "Cochabamba",
      "Cotoca",
      "Cruz",
      "Guayaramerin",
      "La Paz",
      "Oruro",
      "Riberalta",
      "Santa Cruz",
      "Santa Cruz",
      "Sucre",
      "Tarija",
      "Trinidad",
    ],
  },
  {
    id: 21,
    country: "Bosnia and Herzegovina",
    cities: [
      "Banja",
      "Banja Luka",
      "Bijeljina",
      "Bosanska Dubica",
      "Bosanska Krupa",
      "Brcko",
      "Breza",
      "Bugojno",
      "Cazin",
      "Core",
      "Doboj",
      "Donja Mahala",
      "Gracanica",
      "Ilidza",
      "Jajce",
      "Jelah",
      "Kiseljak",
      "Livno",
      "Ljubuski",
      "Lopare",
      "Lukavac",
      "Modrica",
      "Mostar",
      "Novi Travnik",
      "Odzak",
      "Prijedor",
      "Sanski Most",
      "Sarajevo",
      "Siroki Brijeg",
      "Srpska",
      "Stup",
      "Tesanj",
      "Travnik",
      "Tuzla",
      "Visoko",
      "Vitez",
      "Vogosca",
      "Zenica",
      "Zepce",
      "Zivinice",
    ],
  },
  {
    id: 22,
    country: "Botswana",
    cities: ["Francistown", "Gaborone", "Orapa", "Serowe", "Village"],
  },
  {
    id: 23,
    country: "Brazil",
    cities: [
      "Abadiania",
      "Abaetetuba",
      "Abelardo Luz",
      "Abidos",
      "Abrantes",
      "Abreu",
      "Abreu e Lima",
      "Acarau",
      "Acopiara",
      "Acorizal",
      "Acu",
      "Acucena",
      "Adamantina",
      "Adustina",
      "Afogados da Ingazeira",
      "Afonso Claudio",
      "Agrestina",
      "Agua Boa",
      "Agua Clara",
      "Aguai",
      "Aguanil",
      "Aguas Claras",
      "Aguas da Prata",
      "Aguas de Chapeco",
      "Aguas de Lindoia",
      "Aguas de Sao Pedro",
      "Aguas Lindas",
      "Agudo",
      "Agudos",
      "Agulha",
      "Alagoa Grande",
      "Alagoa Nova",
      "Alagoinha",
      "Alagoinhas",
      "Alambari",
      "Aldeia",
      "Alegre",
      "Alegres",
      "Alegrete",
      "Alem Paraiba",
      "Alfenas",
      "Alfredo Chaves",
      "Almeirim",
      "Almirante Tamandare",
      "Aloandia",
      "Alta Floresta",
      "Altamira",
      "Altaneira",
      "Alterosa",
      "Altinho",
      "Altinopolis",
      "Alto",
      "Alto Alegre",
      "Alto do Rodrigues",
      "Alto Paraiso de Goias",
      "Alto Piquiri",
      "Alto Santo",
      "Altos",
      "Alvares Machado",
      "Alvorada",
      "Alvorada do Sul",
      "Amambai",
      "Amaraji",
      "Amarante",
      "Amarante do Maranhao",
      "Amazonas",
      "America de Cima",
      "America Dourada",
      "Americana",
      "Americo Brasiliense",
      "Amparo",
      "Anadia",
      "Anajas",
      "Ananindeua",
      "Anchieta",
      "Andarai",
      "Andradas",
      "Andradina",
      "Andre",
      "Andre da Rocha",
      "Angatuba",
      "Angical do Piaui",
      "Angicos",
      "Angra dos Reis",
      "Anhembi",
      "Anhumas",
      "Antas",
      "Antonina",
      "Antonio Carlos",
      "Antonio Carlos",
      "Antonio Prado",
      "Aparecida",
      "Aparecida do Rio Negro",
      "Aperibe",
      "Apiai",
      "Apiuna",
      "Apodi",
      "Apora",
      "Apucarana",
      "Apuiares",
    ],
  },
  {
    id: 24,
    country: "Brunei",
    cities: [
      "Bandar Seri Begawan",
      "Bangar",
      "Kampong Jerudong",
      "Kuala Balai",
      "Kuala Belait",
      "Panaga",
      "Seria",
      "Tutong",
    ],
  },
  {
    id: 25,
    country: "Bulgaria",
    cities: [
      "Akhtopol",
      "Aksakovo",
      "Aleksandriya",
      "Alfatar",
      "Anton",
      "Antonovo",
      "Ardino",
      "Asenovgrad",
      "Aytos",
      "Babovo",
      "Baltchik",
      "Banite",
      "Bankya",
      "Bansko",
      "Barutin",
      "Batak",
      "Belene",
      "Belogradchik",
      "Beloslav",
      "Belovo",
      "Berkovitsa",
      "Bistritsa",
      "Blagoevgrad",
      "Boboshevo",
      "Bobovdol",
      "Borovan",
      "Borovo",
      "Botevgrad",
      "Bratsigovo",
      "Bregare",
      "Bukovo",
      "Bukovo",
      "Burgas",
      "Byala",
      "Byala",
      "Byala Slatina",
      "Chakalarovo",
      "Chernolik",
      "Chernomorets",
      "Cherven",
      "Cherven Bryag",
      "Chiprovtsi",
      "Chirpan",
      "Choba",
      "Debelets",
      "Devin",
      "Dimitrovgrad",
      "Dobrich",
      "Dolna Banya",
      "Dolna Mitropoliya",
      "Dolna Oryakhovitsa",
      "Dospat",
      "Dragash Voyvoda",
      "Draginovo",
      "Dragizhevo",
      "Dryanovo",
      "Dulgopol",
      "Dulovo",
      "Dupnitsa",
      "Elena",
      "Elin Pelin",
      "Elkhovo",
      "Etropole",
      "Gabrovo",
      "Ganchovo",
      "General-Toshevo",
      "Glogovo",
      "Godech",
      "Gorna Oryakhovitsa",
      "Gotse Delchev",
      "Gulubovo",
      "Gurkovo",
      "Gurmazovo",
      "Haskovo",
      "Ikhtiman",
      "Iskrets",
      "Isperikh",
      "Isperikhovo",
      "Ivaylovgrad",
      "Kableshkovo",
      "Kamenovo",
      "Kardzhali",
      "Karlovo",
      "Karnobat",
      "Kavarna",
      "Kazanlak",
      "Kazashka Reka",
      "Kharmanli",
      "Khisarya",
      "Knezha",
      "Konush",
      "Koprivets",
      "Koprivlen",
      "Kostenets",
      "Kostievo",
      "Kostinbrod",
      "Kovachite",
      "Kozloduy",
      "Kran",
      "Krichim",
    ],
  },
  {
    id: 26,
    country: "Cambodia",
    cities: [
      "Moung Roessei",
      "Phnom Penh",
      "Phumi Boeng (1)",
      "Phumi Chhuk",
      "Phumi Preah Haoh",
      "Phumi Prei",
      "Phumi Prek Mrinh",
      "Phumi Siem Reab",
      "Phumi Thmei",
      "Phumi Thnal",
      "Phumi Vott Phnum",
      "Sihanoukville",
      "Tuol Kok",
      "Vott Kampong Svay",
    ],
  },
  {
    id: 27,
    country: "Cameroon",
    cities: [
      "Bafia",
      "Bafoussam",
      "Bamenda",
      "Buea",
      "Douala",
      "Kribi",
      "Kumba",
      "Ringo",
      "Tibati",
    ],
  },
  {
    id: 28,
    country: "Canada",
    cities: [
      "100 Mile House",
      "Abbey",
      "Abbotsford",
      "Acadia Valley",
      "Acme",
      "Acton",
      "Acton Vale",
      "Agassiz",
      "Agincourt",
      "Ailsa Craig",
      "Airdrie",
      "Ajax",
      "Aklavik",
      "Alameda",
      "Albanel",
      "Alberton",
      "Aldergrove",
      "Alert Bay",
      "Alexander",
      "Alexandria",
      "Alfred",
      "Allan",
      "Allardville",
      "Allenford",
      "Alliston",
      "Alma",
      "Alma",
      "Almonte",
      "Alton",
      "Altona",
      "Alvinston",
      "Amherst",
      "Amherstburg",
      "Amos",
      "Amqui",
      "Ancaster",
      "Andrew",
      "Ange-Gardien",
      "Angliers",
      "Angus",
      "Annapolis Royal",
      "Antigonish",
      "Apohaqui",
      "Apple Hill",
      "Apsley",
      "Arborfield",
      "Arborg",
      "Arcadia",
      "Arcola",
      "Arctic Bay",
      "Ardmore",
      "Ardrossan",
      "Arelee",
      "Arichat",
      "Arkona",
      "Armagh",
      "Armstrong",
      "Arnprior",
      "Arthabaska",
      "Arthur",
      "Arundel",
      "Arva",
      "Arviat",
      "Asbestos",
      "Ascot Corner",
      "Ashcroft",
      "Ashmont",
      "Ashville",
      "Assiniboia",
      "Aston-Jonction",
      "Athabasca",
      "Athens",
      "Atikameg",
      "Atikokan",
      "Atlin",
      "Attawapiskat",
      "Atwood",
      "Audet",
      "Aurora",
      "Austin",
      "Authier",
      "Avonmore",
      "Aylesford",
      "Aylmer",
      "Aylmer",
      "Aylsham",
      "Ayr",
      "Ayton",
      "Baddeck",
      "Baden",
      "Baie Verte",
      "Baie-Comeau",
      "Baie-Des-Sables",
      "Baie-du-Febvre",
      "Baie-Saint-Paul",
      "Baie-Sainte-Catherine",
      "Bala",
      "Balcarres",
      "Baldonnel",
      "Baldur",
    ],
  },
  {
    id: 29,
    country: "Cayman Islands",
    cities: [
      "Bodden Town",
      "Coral Gables",
      "George Town",
      "Newlands",
      "Savannah",
      "Spot Bay",
      "West Bay",
    ],
  },
  {
    id: 30,
    country: "Chile",
    cities: [
      "Algarrobo",
      "Angol",
      "Antofagasta",
      "Apoquindo",
      "Arauco",
      "Arica",
      "Buin",
      "Bulnes",
      "Calama",
      "Caldera",
      "Castro",
      "Catemu",
      "Centro",
      "Cerrillos de Tamaya",
      "Chicureo Abajo",
      "Chiguayante",
      "Chillan",
      "Chillan Viejo",
      "Chimbarongo",
      "Chonchi",
      "Chuquicamata",
      "Coihaique",
      "Colina",
      "Collipulli",
      "Concon",
      "Constitucion",
      "Coquimbo",
      "Coronel",
      "Cunco",
      "Curacavi",
      "Dalcahue",
      "El Arco",
      "El Bosque",
      "El Monte",
      "El Quisco",
      "El Salto",
      "El Salvador",
      "El Valle",
      "Fresia",
      "Galvarino",
      "Graneros",
      "Hanga Roa",
      "Iquique",
      "La Calera",
      "La Cisterna",
      "La Granja",
      "La Laja",
      "La Ligua",
      "La Reina",
      "La Serena",
      "La Union",
      "Lampa",
      "Las Condes",
      "Lautaro",
      "Llanquihue",
      "Lo Barnechea",
      "Lolol",
      "Los Andes",
      "Los Angeles",
      "Machali",
      "Macul",
      "Maipu",
      "Maquina Atacama",
      "Maule",
      "Mejillones",
      "Melipilla",
      "Miraflores",
      "Molina",
      "Monte Aguila",
      "Nacimiento",
      "Nogales",
      "Nunoa",
      "Olmue",
      "Osorno",
      "Ovalle",
      "Paillaco",
      "Penablanca",
      "Penaflor",
      "Port Montt",
      "Providencia",
      "Puchuncavi",
      "Pucon",
      "Puente Alto",
      "Puerto Aisen",
      "Puerto Natales",
      "Puerto Varas",
      "Punta Arenas",
      "Puren",
      "Purranque",
      "Quellon",
      "Quemchi",
      "Quilicura",
      "Quillota",
      "Rancagua",
      "Recoleta",
      "Renaca",
      "Renca",
      "Rengo",
      "Rinconada",
      "Rio Bueno",
    ],
  },
  {
    id: 31,
    country: "China",
    cities: [
      "Aishang",
      "Aizhou",
      "Aksu",
      "Anbang",
      "Anbu",
      "Ancheng",
      "Anda",
      "Andong",
      "Angu",
      "Anguo",
      "Anhu",
      "Anji",
      "Anjiang",
      "Ankang",
      "Anke",
      "Anqing",
      "Anqiu",
      "Anshan",
      "Anshun",
      "Ansu",
      "Anxi",
      "Anyang",
      "Anying",
      "Anzhou",
      "Anzi",
      "Aojiang",
      "Aoma",
      "Bagong",
      "Baicheng",
      "Baidu",
      "Baihua",
      "Baile",
      "Bailicun",
      "Baipo",
      "Baise City",
      "Baisha",
      "Baishan",
      "Baishi",
      "Baitang",
      "Baixiang",
      "Baixin",
      "Baiyashi",
      "Baiyi",
      "Baiyin",
      "Baiyu",
      "Baiyun",
      "Baizhang",
      "Baliqiao",
      "Bamao",
      "Bangke",
      "Bangtou",
      "Bantou",
      "Banxi",
      "Banyou",
      "Baocheng",
      "Baodi",
      "Baodian",
      "Baoding",
      "Baojiang",
      "Baoluo",
      "Baoqing",
      "Baoshan",
      "Baotao",
      "Baotian",
      "Baotou",
      "Baotou",
      "Baoxing",
      "Baoyu",
      "Base",
      "Baying",
      "Bazhou",
      "Baziqiang",
      "Beichan",
      "Beidou",
      "Beihai",
      "Beijie",
      "Beijing",
      "Beilin",
      "Beilun",
      "Beishan",
      "Beixi",
      "Beixiao",
      "Beiying",
      "Beiyuan",
      "Beiyuan",
      "Bengbu",
      "Benxi",
      "Bianzhuang",
      "Bibo",
      "Bijie",
      "Binhe",
      "Binjiang",
      "Binzhou",
      "Biyang",
      "Bobai",
      "Bohai",
      "Boji",
      "Bole",
      "Bole",
      "Boli",
    ],
  },
  {
    id: 32,
    country: "Colombia",
    cities: [
      "Acacias",
      "Acevedo",
      "Aguachica",
      "Antioquia",
      "Arauca",
      "Armenia",
      "Atlantico",
      "Barrancabermeja",
      "Barranquilla",
      "Bello",
      "Bermudez",
      "Boyaca",
      "Bucaramanga",
      "Buenaventura",
      "Buga",
      "Cajica",
      "Calamar",
      "Caldas",
      "Candelaria",
      "Cartagena",
      "Cartago",
      "Cauca",
      "Chia",
      "Chiquinquira",
      "Chocho",
      "Columbia",
      "Corozal",
      "Cota",
      "Cumaribo",
      "Cundinamarca",
      "Dosquebradas",
      "Duitama",
      "El Colegio",
      "Engativa",
      "Envigado",
      "Espinal",
      "Florencia",
      "Floridablanca",
      "Fonseca",
      "Fundacion",
      "Fusagasuga",
      "Galapa",
      "Ginebra",
      "Giron",
      "Guarne",
      "Ibague",
      "Inirida",
      "Ipiales",
      "Itagui",
      "La Ceja",
      "La Estrella",
      "La Mesa",
      "La Union",
      "Los Patios",
      "Madrid",
      "Magdalena",
      "Manizales",
      "Miami",
      "Mitu",
      "Montenegro",
      "Mosquera",
      "Municipio de Copacabana",
      "Neiva",
      "Obando",
      "Palmira",
      "Pamplona",
      "Pasto",
      "Pereira",
      "Piedecuesta",
      "Pitalito",
      "Planadas",
      "Popayan",
      "Puerta Roja",
      "Puerto Tejada",
      "Purificacion",
      "Riohacha",
      "Rionegro",
      "Risaralda",
      "Sabana de Torres",
      "Sabaneta",
      "Sachica",
      "San Clemente",
      "San Diego",
      "San Gil",
      "San Martin",
      "Santa Marta",
      "Santa Rosa de Cabal",
      "Santa Rosa del Sur",
      "Santiago de Cali",
      "Silvania",
      "Sincelejo",
      "Soacha",
      "Sogamoso",
      "Soledad",
      "Sopo",
      "Tarapaca",
      "Tauramena",
      "Tenjo",
      "Tocancipa",
      "Tunja",
    ],
  },
  {
    id: 33,
    country: "Congo",
    cities: ["Banana", "Goma", "Kinshasa", "Likasi", "Lubumbashi"],
  },
  {
    id: 34,
    country: "Costa Rica",
    cities: [
      "Alajuela",
      "Alajuelita",
      "Alfaro",
      "Aserri",
      "Atenas",
      "Barva",
      "Cartago",
      "Colon",
      "Corazon de Jesus",
      "Coronado",
      "Coyol",
      "Curridabat",
      "Desamparados",
      "Escazu",
      "Esparza",
      "Filadelfia",
      "Grecia",
      "Guachipelin",
      "Guacima",
      "Guadalupe",
      "Guapiles",
      "Heredia",
      "Isla de Tibas",
      "Jaco",
      "La Garita",
      "Liberia",
      "Llorente",
      "Llorente",
      "Mercedes",
      "Mexico",
      "Miramar",
      "Moravia",
      "Palmares",
      "Paraiso",
      "Pavas",
      "Perez",
      "Poas",
      "Puerto Jimenez",
      "Puntarenas",
      "Quepos",
      "Quesada",
      "Sabanilla",
      "San Diego",
      "San Francisco",
      "San Francisco",
      "San Isidro",
      "San Joaquin",
      "San Jose de la Montana",
      "San Josecito",
      "San Juan",
      "San Marcos",
      "San Pablo",
      "San Pedro",
      "San Rafael",
      "San Rafael",
      "San Ramon",
      "Santa Ana",
      "Santa Cecilia",
      "Santa Cruz",
      "Santo Domingo",
      "Sarchi",
      "Siquirres",
      "Tres Rios",
      "Turrialba",
      "Turrucares",
      "Zapote",
      "Zarcero",
    ],
  },
  {
    id: 35,
    country: "Croatia",
    cities: [
      "Antunovac",
      "Baska",
      "Baska Voda",
      "Bedekovcina",
      "Bestovje",
      "Betina",
      "Bibinje",
      "Bizovac",
      "Bjelovar",
      "Bracevci",
      "Brdovec",
      "Bregana",
      "Brela",
      "Brsadin",
      "Buje",
      "Cabuna",
      "Cavtat",
      "Cepin",
      "Cestica",
      "Core",
      "Crikvenica",
      "Dalj",
      "Darda",
      "Delnice",
      "Desinic",
      "Donja Pusca",
      "Donja Zelina",
      "Donji Kraljevec",
      "Dubrovnik",
      "Dugo Selo",
      "Fazana",
      "Fuzine",
      "Galgovo",
      "Glina",
      "Gornja Lomnica",
      "Gornji Kriz",
      "Gornji Stupnik",
      "Hreljin",
      "Icici",
      "Ivanec",
      "Ivanic-Grad",
      "Karlovac",
      "Karojba",
      "Kastel Gomilica",
      "Kastel Luksic",
      "Kastel Sucurac",
      "Koprivnica",
      "Kostrena",
      "Kraljevec na Sutli",
      "Krapina",
      "Kriz",
      "Krk",
      "Krsan",
      "Kutjevo",
      "Labin",
      "Lapad",
      "Lekenik",
      "Lepoglava",
      "Lovran",
      "Lukavec",
      "Lupoglav",
      "Lupoglav",
      "Makarska",
      "Matulji",
      "Medulin",
      "Mlini",
      "Mursko Sredisce",
      "Nedelisce",
      "Nova Gradiska",
      "Novi Marof",
      "Novi Vinodolski",
      "Novo Cice",
      "Nustar",
      "Okrug Gornji",
      "Opatija",
      "Orahovica",
      "Orebic",
      "Orle",
      "Oroslavje",
      "Osijek",
      "Pakrac",
      "Pazin",
      "Petrcane",
      "Petrinja",
      "Piskorevci",
      "Podastrana",
      "Podgajci Posavski",
      "Popovaca",
      "Postira",
      "Pregrada",
      "Prelog",
      "Primosten",
      "Privlaka",
      "Pula",
      "Rab",
      "Rakitje",
      "Rijeka",
      "Rijeka",
      "Rovinj",
      "Samobor",
    ],
  },
  {
    id: 36,
    country: "Cuba",
    cities: [
      "Bayamo",
      "Cienfuegos",
      "Habana",
      "Havana",
      "La Habana",
      "Las Tunas",
      "Matanzas",
      "Santiago de Cuba",
      "Varadero",
      "Villa",
    ],
  },
  {
    id: 37,
    country: "Cyprus",
    cities: [
      "Agia Anna",
      "Aradippou",
      "Ayia Marina",
      "Chlorakas",
      "Deryneia",
      "Famagusta",
      "Geroskipou",
      "Kato Lakatamia",
      "Kato Polemidia",
      "Kiti",
      "Kyrenia",
      "Larnaca",
      "Laxia",
      "Limassol",
      "Livadia",
      "Morfou",
      "Mouttagiaka",
      "Nicosia",
      "Paphos",
      "Paralimni",
      "Parekklisha",
      "Prodromi",
      "Sotira",
      "Strovolos",
      "Tera",
    ],
  },
  {
    id: 38,
    country: "Czech Republic",
    cities: [
      "Adamov",
      "Albrechtice",
      "Arnoltice",
      "As",
      "Babice",
      "Banov",
      "Baska",
      "Batelov",
      "Bavory",
      "Bechyne",
      "Bela pod Bezdezem",
      "Belotin",
      "Benatky nad Jizerou",
      "Benesov",
      "Benesovice",
      "Bernartice",
      "Bernartice nad Odrou",
      "Beroun",
      "Bezdekov",
      "Bilina",
      "Bilina",
      "Bilovice",
      "Bilovice nad Svitavou",
      "Bitovany",
      "Blansko",
      "Blatna",
      "Blizevedly",
      "Blovice",
      "Blucina",
      "Bludov",
      "Bludovice",
      "Bochov",
      "Bohumin",
      "Bohunovice",
      "Bojanov",
      "Bojkovice",
      "Bolatice",
      "Bolebor",
      "Bor",
      "Boretice",
      "Borohradek",
      "Borotin",
      "Borovany",
      "Borsice",
      "Bosin",
      "Boskovice",
      "Bradlec",
      "Brandys nad Labem-Stara Boleslav",
      "Branky",
      "Branov",
      "Bratrikov",
      "Brezi",
      "Brezno",
      "Brezolupy",
      "Brezova",
      "Brno",
      "Brod",
      "Brodce",
      "Brodek",
      "Broumov",
      "Brtnice",
      "Bruntal",
      "Brusperk",
      "Bucovice",
      "Budyne nad Ohri",
      "Bukovec",
      "Bustehrad",
      "Bylnice",
      "Bystrice",
      "Bystrice",
      "Bystrice",
      "Bystrice nad Pernstejnem",
      "Bystrice pod Hostynem",
      "Cakovice",
      "Caslav",
      "Cebin",
      "Cechtice",
      "Cejc",
      "Cejkovice",
      "Celadna",
      "Celakovice",
      "Cepi",
      "Cercany",
      "Cerekvice nad Loucnou",
      "Cerhenice",
      "Cerna Hora",
      "Cerna za Bory",
      "Cerncice",
      "Cernosice",
      "Cernotin",
      "Cervene Pecky",
      "Cerveny Kostelec",
      "Ceska",
      "Ceska Skalice",
      "Ceska Trebova",
      "Ceska Ves",
      "Ceske Mezirici",
      "Cesky Brod",
      "Cesky Dub",
      "Cestice",
    ],
  },
  {
    id: 39,
    country: "Denmark",
    cities: [
      "Aabenraa",
      "Aabybro",
      "Aalborg",
      "Aarhus",
      "Aars",
      "Abyhoj",
      "Agedrup",
      "Agerbaek",
      "Agerskov",
      "Akirkeby",
      "Albaek",
      "Albertslund",
      "Ale",
      "Alestrup",
      "Aller",
      "Allerod",
      "Allingabro",
      "Allinge",
      "Almind",
      "Alsgarde",
      "Alslev",
      "Alslev",
      "Anholt",
      "Ans",
      "Ansager",
      "Arden",
      "Arre",
      "Arslev",
      "Arslev",
      "Arup",
      "Asa",
      "Askeby",
      "Asnaes",
      "Asperup",
      "Assens",
      "Astrup",
      "Augustenborg",
      "Auning",
      "Avlum",
      "Baekke",
      "Baekmarksbro",
      "Baelum",
      "Bagsvaerd",
      "Balle",
      "Ballerup",
      "Bandholm",
      "Baring",
      "Barrit",
      "Beder",
      "Bedsted",
      "Bevtoft",
      "Billund",
      "Bjaert",
      "Bjaeverskov",
      "Bjerringbro",
      "Blavand",
      "Blokhus",
      "Blommenslyst",
      "Boeslunde",
      "Bogense",
      "Bogo By",
      "Bolderslev",
      "Bording Stationsby",
      "Borkop",
      "Borre",
      "Borum",
      "Borup",
      "Bovlingbjerg",
      "Bovrup",
      "Brabrand",
      "Braedstrup",
      "Bramming",
      "Brande",
      "Branderup",
      "Bredballe",
      "Bredebro",
      "Bredsten",
      "Brejning",
      "Brenderup",
      "Broager",
      "Brobyvaerk",
      "Brondby Strand",
      "Bronshoj",
      "Brorup",
      "Brovst",
      "Bruunshab",
      "Bryrup",
      "Bylderup-Bov",
      "Charlottenlund",
      "Christiansfeld",
      "Copenhagen",
      "Dalmose",
      "Dannemare",
      "Daugard",
      "Dianalund",
      "Dong",
      "Dronninglund",
      "Dronningmolle",
      "Dybvad",
      "Ebberup",
    ],
  },
  {
    id: 40,
    country: "Dominican Republic",
    cities: [
      "Arenazo",
      "Bavaro",
      "Boca Chica",
      "Cabarete",
      "Cotui",
      "Dominica",
      "Guaricano",
      "Hato Mayor del Rey",
      "Jimani",
      "La Romana",
      "Los Alcarrizos",
      "Los Prados",
      "Moca",
      "Pedernales",
      "Puerto Plata",
      "Punta Cana",
      "Sabaneta",
      "San Cristobal",
      "San Fernando de Monte Cristi",
      "San Jose de Ocoa",
      "Santa Cruz de Barahona",
      "Santiago de los Caballeros",
      "Santo Domingo",
    ],
  },
  {
    id: 41,
    country: "Ecuador",
    cities: [
      "Ambato",
      "Atacames",
      "Atuntaqui",
      "Bahia de Caraquez",
      "Banos",
      "Calderon",
      "Cayambe",
      "Cuenca",
      "Daule",
      "El Carmen",
      "El Naranjal",
      "Esmeraldas",
      "Florida",
      "General Leonidas Plaza Gutierrez",
      "Guabo",
      "Gualaceo",
      "Guamote",
      "Guayaquil",
      "Guayas",
      "Guayllabamba",
      "Hacienda Bolivia",
      "Hacienda Duran",
      "Hacienda Ibarra",
      "Hacienda Santa Catalina",
      "Huaquillas",
      "Ibarra",
      "Jipijapa",
      "La Esperanza",
      "La Libertad",
      "La Troncal",
      "Latacunga",
      "Loja",
      "Loreto",
      "Macara",
      "Macas",
      "Machachi",
      "Machala",
      "Manta",
      "Milagro",
      "Montecristi",
      "Nabon",
      "Olmedo",
      "Otavalo",
      "Paccha",
      "Pasaje",
      "Pelileo",
      "Pichincha",
      "Playas",
      "Portoviejo",
      "Puerto Francisco de Orellana",
      "Puyo",
      "Quevedo",
      "Quito",
      "Riobamba",
      "Salinas",
      "Samborondon",
      "San Miguel",
      "San Rafael",
      "Santa Cruz",
      "Santa Elena",
      "Santo Domingo de los Colorados",
      "Sucre",
      "Tababela",
      "Tarapoa",
      "Tena",
      "Vinces",
      "Zamora",
      "Zaruma",
      "Zumba",
    ],
  },
  {
    id: 42,
    country: "Egypt",
    cities: [
      "Abu Hammad",
      "Al Mahallah al Kubra",
      "Al Mansurah",
      "Al Marj",
      "Alexandria",
      "Almazah",
      "Ar Rawdah",
      "Assiut",
      "Az Zamalik",
      "Badr",
      "Banha",
      "Bani Suwayf",
      "Cairo",
      "Damietta",
      "Faraskur",
      "Flaminj",
      "Giza",
      "Heliopolis",
      "Helwan",
      "Hurghada",
      "Ismailia",
      "Kafr ash Shaykh",
      "Luxor",
      "Madinat an Nasr",
      "Madinat as Sadis min Uktubar",
      "Minya",
      "Nasr",
      "New Cairo",
      "Port Said",
      "Rafah",
      "Ramsis",
      "Sadat",
      "Shirbin",
      "Shubra",
      "Sohag",
      "Suez",
      "Tanta",
      "Toukh",
      "Zagazig",
    ],
  },
  {
    id: 43,
    country: "El Salvador",
    cities: [
      "Ahuachapan",
      "Antiguo Cuscatlan",
      "Apaneca",
      "Apopa",
      "Ayutuxtepeque",
      "Botoncillal El Botoncillo",
      "Coatepeque",
      "Colon",
      "Colonia Escalon",
      "Cuscatancingo",
      "Delgado",
      "Gigante",
      "Guazapa",
      "Ilopango",
      "La Libertad",
      "Lourdes",
      "Mejicanos",
      "Nuevo Cuscatlan",
      "Ozatlan",
      "San Jose Villanueva",
      "San Marcos",
      "San Miguel",
      "San Salvador",
      "Santa Ana",
      "Santa Tecla",
      "Santiago Texacuangos",
      "Sonsonate",
      "Soyapango",
      "Usulutan",
      "Zaragoza",
    ],
  },
  {
    id: 44,
    country: "Estonia",
    cities: [
      "Aasmae",
      "Aaviku",
      "Aespa",
      "Ahtma",
      "Alliku",
      "Ambla",
      "Antsla",
      "Ardu",
      "Avinurme",
      "Elva",
      "Emmaste",
      "Haabneeme",
      "Haage",
      "Haapsalu",
      "Halinga",
      "Harju",
      "Harku",
      "Kaarma",
      "Kadrina",
      "Kehra",
      "Keila",
      "Kiili",
      "Kohila",
      "Kohtla",
      "Kose",
      "Kulna",
      "Kuressaare",
      "Kuusalu",
      "Laagri",
      "Lagedi",
      "Lahtse",
      "Lepna",
      "Loksa",
      "Loo",
      "Lubja",
      "Maardu",
      "Muraste",
      "Narva",
      "Otepaeae",
      "Paide",
      "Paikuse",
      "Paldiski",
      "Palivere",
      "Peetri",
      "Puhja",
      "Rakke",
      "Rakvere",
      "Rapla",
      "Saku",
      "Saue",
      "Sindi",
      "Somerpalu",
      "Syare",
      "Tabasalu",
      "Tabivere",
      "Tallinn",
      "Tamsalu",
      "Tapa",
      "Tartu",
      "Toila",
      "Vaida",
      "Valga",
      "Vara",
      "Venevere",
      "Viimsi",
      "Viljandi",
      "Voka",
    ],
  },
  {
    id: 45,
    country: "Faroe Islands",
    cities: [
      "Argir",
      "Glyvrar",
      "Hvalba",
      "Innan Glyvur",
      "Leirvik",
      "Saltangara",
      "Signabour",
      "Strendur",
    ],
  },
  {
    id: 46,
    country: "Finland",
    cities: [
      "Aapajoki",
      "Aavasaksa",
      "Aitoo",
      "Akaa",
      "Alastaro",
      "Alaveteli",
      "Alavieska",
      "Alavus",
      "Alvettula",
      "Angelniemi",
      "Anjala",
      "Anttila",
      "Askola",
      "Aura",
      "Bergoe",
      "Box",
      "Broby",
      "Degerby",
      "Eno",
      "Erajarvi",
      "Espoo",
      "Eura",
      "Eurajoki",
      "Evijaervi",
      "Evitskog",
      "Fiskars",
      "Forsby",
      "Forssa",
      "Gammelby",
      "Haapavesi",
      "Haeme",
      "Haermae",
      "Haijaa",
      "Halikko",
      "Halkia",
      "Halli",
      "Halsua",
      "Hamina",
      "Hammaslahti",
      "Hanko",
      "Harjavalta",
      "Harviala",
      "Hattula",
      "Hauho",
      "Haukipudas",
      "Haukkala",
      "Hausjaervi",
      "Heimari",
      "Heinola",
      "Helsingby",
      "Helsinki",
      "Hervanta",
      "Hiltulanlahti",
      "Himanka",
      "Hinthaara",
      "Hirvensalmi",
      "Hirvihaara",
      "Hoegsara",
      "Hoeytiae",
      "Hollola",
      "Hollola",
      "Huittinen",
      "Humppila",
      "Huuvari",
      "Hyvinkaeae",
      "Ihode",
      "Ii",
      "Iisalmi",
      "Iittala",
      "Ilkka",
      "Ilmajoki",
      "Ilmarinen",
      "Ilveskylae",
      "Imatra",
      "Inkeroinen",
      "Isojoki",
      "Itaekylae",
      "Ivalo",
      "Jaervelae",
      "Jakobstad",
      "Janakkala",
      "Joensuu",
      "Jokela",
      "Jokikunta",
      "Jokimaa",
      "Jokioinen",
      "Jormua",
      "Joroinen",
      "Jorvas",
      "Joutseno",
      "Jurva",
      "Juuka",
      "Juupajoki",
      "Jyskae",
      "Kaakamo",
      "Kaarina",
      "Kaemmenniemi",
      "Kaerrby",
      "Kaipiainen",
      "Kaipola",
    ],
  },
  {
    id: 47,
    country: "France",
    cities: [
      "Aast",
      "Abancourt",
      "Abbans-Dessus",
      "Abbaretz",
      "Abbecourt",
      "Abbeville",
      "Abbeville-les-Conflans",
      "Abeilhan",
      "Abere",
      "Abergement-Saint-Jean",
      "Abilly",
      "Ablain-Saint-Nazaire",
      "Ablaincourt-Pressoir",
      "Ablainzevelle",
      "Ablis",
      "Ablon-sur-Seine",
      "Abondance",
      "Abondant",
      "Abreschviller",
      "Abrest",
      "Abscon",
      "Abzac",
      "Abzac",
      "Achatel",
      "Achenheim",
      "Acheres",
      "Acheville",
      "Achicourt",
      "Achiet-le-Grand",
      "Achiet-le-Petit",
      "Acigne",
      "Acq",
      "Acquigny",
      "Acy-en-Multien",
      "Adam-les-Vercel",
      "Adamswiller",
      "Adelans-et-le-Val-de-Bithaine",
      "Adissan",
      "Adriers",
      "Afa",
      "Agay",
      "Agde",
      "Agen",
      "Agneaux",
      "Agnetz",
      "Agnin",
      "Agnos",
      "Agny",
      "Aguilcourt",
      "Ahaxe-Alciette-Bascassan",
      "Ahuille",
      "Ahun",
      "Ahuy",
      "Aiffres",
      "Aigaliers",
      "Aiglemont",
      "Aignan",
      "Aigne",
      "Aigny",
      "Aigonnay",
      "Aigre",
      "Aigrefeuille",
      "Aigrefeuille-sur-Maine",
      "Aigremont",
      "Aigremont",
      "Aiguebelette-le-Lac",
      "Aiguebelle",
      "Aigueblanche",
      "Aiguefonde",
      "Aigueperse",
      "Aigueperse",
      "Aigues-Mortes",
      "Aigues-Vives",
      "Aigues-Vives",
      "Aiguillon",
      "Ailette",
      "Aillas",
      "Aillevillers-et-Lyaumont",
      "Aillon-le-Vieux",
      "Ailly-le-Haut-Clocher",
      "Ailly-sur-Noye",
      "Ailly-sur-Somme",
      "Aimargues",
      "Aime",
      "Ainay-le-Chateau",
      "Aincourt",
      "Ainhoa",
      "Airaines",
      "Aire-sur-la-Lys",
      "Airel",
      "Airvault",
      "Aiserey",
      "Aissey",
      "Aiton",
      "Aix-en-Ergny",
      "Aix-en-Issart",
      "Aix-en-Othe",
      "Aix-en-Provence",
      "Aix-les-Bains",
      "Aix-Noulette",
    ],
  },
  {
    id: 48,
    country: "French Polynesia",
    cities: ["Arue", "Faaa", "Mahina", "Paeau", "Papeete", "Pirae", "Punaauia"],
  },
  {
    id: 49,
    country: "Gabon",
    cities: ["Gamba", "Libreville", "Mamagnia", "Moanda", "Port-Gentil"],
  },
  {
    id: 50,
    country: "Georgia",
    cities: [
      "Gogolesubani",
      "Kutaisi",
      "Lentekhi",
      "Qazbegi",
      "Samtredia",
      "Sukhumi",
      "Tbilisi",
      "Zemo-Avchala",
      "Zugdidi",
    ],
  },
  {
    id: 51,
    country: "Germany",
    cities: [
      "Aach",
      "Aach",
      "Aachen",
      "Aalen",
      "Abbensen",
      "Abberode",
      "Abenberg",
      "Abensberg",
      "Abstatt",
      "Abtsbessingen",
      "Abtsgmuend",
      "Abtswind",
      "Abtweiler",
      "Achern",
      "Achim",
      "Achstetten",
      "Adelebsen",
      "Adelheidsdorf",
      "Adelmannsfelden",
      "Adelschlag",
      "Adelsdorf",
      "Adelsdorf",
      "Adelsheim",
      "Adelshofen",
      "Adelsried",
      "Adenau",
      "Adenbuettel",
      "Adendorf",
      "Adlkofen",
      "Adlum",
      "Adorf",
      "Aerzen",
      "Affalterbach",
      "Affaltern",
      "Affing",
      "Affinghausen",
      "Aftholderberg",
      "Aglasterhausen",
      "Ahaus",
      "Ahausen",
      "Ahlen",
      "Ahlhorn",
      "Aholfing",
      "Aholming",
      "Ahorn",
      "Ahrbruck",
      "Ahrensboek",
      "Ahrensbok",
      "Ahrensburg",
      "Ahrensfelde",
      "Ahrenshagen",
      "Ahrensmoor",
      "Ahstedt",
      "Aicha vorm Wald",
      "Aichach",
      "Aichelberg",
      "Aichhalden",
      "Aichstetten",
      "Aichtal",
      "Aichwald",
      "Aidenbach",
      "Aidlingen",
      "Aindling",
      "Aindorf",
      "Ainring",
      "Aislingen",
      "Aitrach",
      "Aitrang",
      "Aken",
      "Albaching",
      "Albbruck",
      "Albeck",
      "Albersdorf",
      "Albershausen",
      "Albersweiler",
      "Albertshausen",
      "Albig",
      "Albisheim",
      "Albrechts",
      "Albstadt",
      "Aldekerk",
      "Aldenhoven",
      "Aldersbach",
      "Aldingen",
      "Alesheim",
      "Aletshausen",
      "Alexander",
      "Alfdorf",
      "Alfeld",
      "Alfeld",
      "Alfhausen",
      "Alfstedt",
      "Alfter",
      "Algermissen",
      "Alheim",
      "Allee",
      "Allendorf",
      "Allendorf",
      "Allensbach",
      "Allersberg",
    ],
  },
  {
    id: 52,
    country: "Ghana",
    cities: [
      "Accra",
      "Bawku",
      "Berekum",
      "Bolgatanga",
      "Cape Coast",
      "Home",
      "Koforidua",
      "Kumasi",
      "Legon",
      "Mampong",
      "Navrongo",
      "Sunyani",
      "Takoradi",
      "Tema",
      "Wa",
      "Winneba",
    ],
  },
  {
    id: 53,
    country: "Greece",
    cities: [
      "Aegina",
      "Agioi Anargyroi",
      "Agios Nikolaos",
      "Agrinio",
      "Aigaleo",
      "Aigio",
      "Alexandreia",
      "Alexandroupoli",
      "Aliartos",
      "Alimos",
      "Amaliada",
      "Anavyssos",
      "Andravida",
      "Ano Liosia",
      "Archaia Nemea",
      "Argos",
      "Argostoli",
      "Argyroupoli",
      "Arta",
      "Aspropyrgos",
      "Athens",
      "Attica",
      "Ayios Stefanos",
      "Chalcis",
      "Chania",
      "Chania",
      "Chios",
      "Cholargos",
      "Corfu",
      "Corinth",
      "Dafni",
      "Dionysos",
      "Drama",
      "Ekali",
      "Elassona",
      "Elefsina",
      "Elliniko",
      "Eretria",
      "Farsala",
      "Filippiada",
      "Filothei",
      "Florina",
      "Galatsi",
      "Giannitsa",
      "Glyfada",
      "Gonnoi",
      "Goumenissa",
      "Heraklion",
      "Hydra",
      "Ialysos",
      "Ierapetra",
      "Igoumenitsa",
      "Ioannina",
      "Kaisariani",
      "Kalamaria",
      "Kalamata",
      "Kalamos",
      "Kallithea",
      "Kalymnos",
      "Kamatero",
      "Karditsa",
      "Kassiopi",
      "Kastoria",
      "Katerini",
      "Kavala",
      "Keratea",
      "Keratsini",
      "Kifissia",
      "Kilkis",
      "Komotini",
      "Koropi",
      "Kos",
      "Kouvaras",
      "Kozani",
      "Kranidi",
      "Kryonerion",
      "Kymi",
      "Lamia",
      "Larisa",
      "Lefkada",
      "Lefkimmi",
      "Leontario",
      "Litochoro",
      "Lixouri",
      "Loutraki",
      "Lykovrysi",
      "Magoula",
      "Makrygialos",
      "Mandra",
      "Marathon",
      "Markopoulo Mesogaias",
      "Megalochari",
      "Megara",
      "Melissia",
      "Mesagros",
      "Messolonghi",
      "Metaxades",
      "Moires",
      "Mytilene",
      "Nafpaktos",
    ],
  },
  {
    id: 54,
    country: "Greenland",
    cities: [
      "Aasiaat",
      "Ilulissat",
      "Kapisillit",
      "Maniitsoq",
      "Narsaq",
      "Narsarsuaq",
      "Nuuk",
      "Nuussuaq",
      "Paamiut",
      "Qaqortoq",
      "Qasigiannguit",
      "Qeqertarsuaq",
      "Qeqertat",
      "Sisimiut",
      "Tasiilaq",
      "Upernavik",
      "Uummannaq Kommune",
    ],
  },
  {
    id: 55,
    country: "Guadeloupe",
    cities: [
      "Anse-Bertrand",
      "Baie Mahault",
      "Baie-Mahault",
      "Baillif",
      "Basse-Terre",
      "Capesterre-Belle-Eau",
      "Capesterre-de-Marie-Galante",
      "Deshaies",
      "Gourbeyre",
      "Goyave",
      "Grand-Bourg",
      "Lamentin",
      "Le Gosier",
      "Le Moule",
      "Les Abymes",
      "Petit-Bourg",
      "Petit-Canal",
      "Pointe-Noire",
      "Port-Louis",
      "Saint-Claude",
      "Saint-Francois",
      "Saint-Louis",
      "Sainte-Anne",
      "Sainte-Rose",
      "Terre-de-Bas",
      "Terre-de-Haut",
      "Trois-Rivieres",
      "Village",
    ],
  },
  {
    id: 56,
    country: "Guam",
    cities: [
      "Barrigada Village",
      "Dededo Village",
      "Inarajan Village",
      "Santa Rita",
      "Tamuning-Tumon-Harmon Village",
      "Yigo Village",
    ],
  },
  {
    id: 57,
    country: "Guatemala",
    cities: [
      "Antigua Guatemala",
      "Cambote",
      "Catarina",
      "Central",
      "Chimaltenango",
      "Chiquimula",
      "Ciudad Vieja",
      "Coban",
      "El Limon",
      "El Naranjo",
      "El Salvador",
      "Escuintla",
      "Esquipulas",
      "Flores",
      "Guatemala City",
      "Huehuetenango",
      "Jocotenango",
      "La Reforma",
      "La Reforma",
      "Mazatenango",
      "Melchor de Mencos",
      "Mixco",
      "Palin",
      "Panajachel",
      "Petapa",
      "Puerto Barrios",
      "Quesada",
      "Quetzaltenango",
      "Retalhuleu",
      "San Antonio Miramar",
      "San Jose Pinula",
      "San Juan",
      "San Marcos",
      "San Pedro Sacatepequez",
      "Santa Catarina Pinula",
      "Santa Cruz La Laguna",
      "Santa Cruz Naranjo",
      "Santa Lucia Cotzumalguapa",
      "Santa Rosa",
      "Solola",
      "Villa Nueva",
      "Vista Hermosa",
      "Zacapa",
    ],
  },
  {
    id: 58,
    country: "Guinea",
    cities: [
      "Conakry",
      "Dabola",
      "Kalia",
      "Kankan",
      "Lola",
      "Mamou",
      "Port Kamsar",
      "Sangaredi",
    ],
  },
  {
    id: 59,
    country: "Haiti",
    cities: [
      "Carrefour",
      "Delmar",
      "Duverger",
      "Jacmel",
      "Masseau",
      "Moise",
      "Petionville",
      "Port-au-Prince",
      "Prince",
      "Turgeau",
    ],
  },
  {
    id: 60,
    country: "Hashemite Kingdom of Jordan",
    cities: ["Amman", "Ar Ramtha", "Farah", "Irbid", "Madaba", "Sahab", "Salt"],
  },
  {
    id: 61,
    country: "Honduras",
    cities: [
      "Choloma",
      "Comayagua",
      "Comayaguela",
      "Coxen Hole",
      "El Barro",
      "El Paraiso",
      "El Progreso",
      "La Ceiba",
      "La Hacienda",
      "Morazan",
      "Nacaome",
      "Pinalejo",
      "Piraera",
      "Puerto Lempira",
      "San Antonio de Flores",
      "San Pedro Sula",
      "Santa Barbara",
      "Sula",
      "Tegucigalpa",
    ],
  },
  {
    id: 62,
    country: "Hong Kong",
    cities: [
      "Aberdeen",
      "Causeway Bay",
      "Central District",
      "Cha Kwo Ling",
      "Chai Wan Kok",
      "Chek Chue",
      "Cheung Kong",
      "Cheung Sha Wan",
      "Chuen Lung",
      "Chung Hau",
      "Fa Yuen",
      "Fanling",
      "Fo Tan",
      "Happy Valley",
      "Ho Man Tin",
      "Hong Kong",
      "Hung Hom",
      "Kat O Sheung Wai",
      "Kennedy Town",
      "Kowloon",
      "Kowloon Tong",
      "Kwai Chung",
      "Kwun Hang",
      "Lai Chi Wo",
      "Lam Tei",
      "Lam Tin",
      "Lin Fa Tei",
      "Lo So Shing",
      "Ma On Shan Tsuen",
      "Ma Wan",
      "Ma Yau Tong",
      "Mau Ping",
      "Mid Levels",
      "Mong Kok",
      "Nam A",
      "Ngau Chi Wan",
      "Ngau Tau Kok",
      "North Point",
      "Pak Ngan Heung",
      "Peng Chau",
      "Ping Yeung",
      "Quarry Bay",
      "Repulse Bay",
      "Sai Keng",
      "San Tsuen",
      "San Tung Chung Hang",
      "Sha Po Kong",
      "Sha Tau Kok",
      "Sha Tin Wai",
      "Sham Shui Po",
      "Sham Tseng",
      "Shatin",
      "Shau Kei Wan",
      "Shek Kip Mei",
      "Shek Tong Tsui",
      "Sheung Shui",
      "Sheung Tsuen",
      "Shuen Wan",
      "Tai Chau To",
      "Tai Hang",
      "Tai Kok Tsui",
      "Tai Lin Pai",
      "Tai Po",
      "Tai Tan",
      "Tai Wai",
      "Tai Wan To",
      "Tin Shui Wai",
      "Tin Wan Resettlement Estate",
      "Ting Kau",
      "To Kwa Wan",
      "Tseung Kwan O",
      "Tsimshatsui",
      "Tsing Lung Tau",
      "Tsz Wan Shan",
      "Tuen Mun San Hui",
      "Wan Tsai",
      "Wo Che",
      "Wong Chuk Hang",
      "Wong Tai Sin",
      "Yau Ma Tei",
      "Ying Pun",
      "Yuen Long San Hui",
    ],
  },
  {
    id: 63,
    country: "Hungary",
    cities: [
      "Abaujszanto",
      "Abda",
      "Abony",
      "Acs",
      "Acsa",
      "Adacs",
      "Adony",
      "Agard",
      "Ajak",
      "Ajka",
      "Alap",
      "Albertirsa",
      "Almasfuzito",
      "Almaskamaras",
      "Almosd",
      "Alsogalla",
      "Alsonemedi",
      "Alsopahok",
      "Alsoszentivan",
      "Alsotold",
      "Alsozsolca",
      "Aparhant",
      "Apatfalva",
      "Apc",
      "Apostag",
      "Arnot",
      "Asotthalom",
      "Aszalo",
      "Aszar",
      "Aszod",
      "Atkar",
      "Attala",
      "Babolna",
      "Bacsalmas",
      "Badacsonytomaj",
      "Badacsonytordemic",
      "Bag",
      "Bagyogszovat",
      "Baja",
      "Bajna",
      "Bakonybel",
      "Bakonycsernye",
      "Bakonyszentlaszlo",
      "Bakonyszombathely",
      "Balassagyarmat",
      "Balaton",
      "Balatonalmadi",
      "Balatonboglar",
      "Balatonfokajar",
      "Balatonfured",
      "Balatonfuzfo",
      "Balatonkenese",
      "Balatonlelle",
      "Balatonszabadi",
      "Balatonszarszo",
      "Balkany",
      "Balloszog",
      "Balmazujvaros",
      "Banhorvati",
      "Baracs",
      "Baracska",
      "Barand",
      "Barcs",
      "Bataszek",
      "Batonyterenye",
      "Bazsi",
      "Becsehely",
      "Bekasmegyer",
      "Bekesszentandras",
      "Belapatfalva",
      "Beled",
      "Beloiannisz",
      "Benye",
      "Berekfurdo",
      "Berettyoujfalu",
      "Berhida",
      "Berkesd",
      "Besnyo",
      "Biatorbagy",
      "Bicske",
      "Biharkeresztes",
      "Bikal",
      "Bocs",
      "Bodajk",
      "Bodaszolo",
      "Bodrogkisfalud",
      "Bogyiszlo",
      "Bohonye",
      "Bokod",
      "Boldog",
      "Boldva",
      "Boly",
      "Boncodfolde",
      "Bonyhad",
      "Borcs",
      "Borsodszirak",
      "Budajeno",
      "Budakalasz",
      "Budakeszi",
      "Budaors",
    ],
  },
  {
    id: 64,
    country: "Iceland",
    cities: [
      "Akranes",
      "Akureyri",
      "Borgarnes",
      "Dalvik",
      "Grindavik",
      "Hella",
      "Holmavik",
      "Husavik",
      "Hvammstangi",
      "Hveragerdi",
      "Hvolsvollur",
      "Kopavogur",
      "Reykjavik",
      "Selfoss",
      "Skagastrond",
      "Stokkseyri",
      "Vestmannaeyjar",
      "Vogar",
    ],
  },
  {
    id: 65,
    country: "India",
    cities: [
      "Abdul",
      "Adilabad",
      "Adwani",
      "Agartala",
      "Agra",
      "Ahmedabad",
      "Ahmednagar",
      "Aizawl",
      "Ajabpur",
      "Ajmer",
      "Akividu",
      "Akola",
      "Alanallur",
      "Alangulam",
      "Alappuzha",
      "Aldona",
      "Alibag",
      "Aligarh",
      "Alipur",
      "Alipur",
      "Allahabad",
      "Almora",
      "Aluva",
      "Alwar",
      "Amal",
      "Amalapuram",
      "Ambad",
      "Ambah",
      "Ambala",
      "Ambarnath",
      "Ambejogai",
      "Ambikapur",
      "Ambur",
      "Amer",
      "Amet",
      "Amravati",
      "Amreli",
      "Amritsar",
      "Anand",
      "Anantapur",
      "Anantnag",
      "Anantpur",
      "Anchal",
      "Andheri",
      "Andra",
      "Angadipuram",
      "Angul",
      "Ankleshwar",
      "Annamalainagar",
      "Antapur",
      "Arakkonam",
      "Arani",
      "Aranmula",
      "Arch",
      "Ariyalur",
      "Arora",
      "Arpora",
      "Arunachal",
      "Arvi",
      "Asansol",
      "Assagao",
      "Attingal",
      "Attur",
      "Aundh",
      "Aurangabad",
      "Aurangabad",
      "Avanigadda",
      "Azamgarh",
      "Baddi",
      "Badlapur",
      "Bagalkot",
      "Bagh",
      "Bagpat",
      "Bahadurgarh",
      "Baharampur",
      "Baidyabati",
      "Bala",
      "Balaghat",
      "Balana",
      "Balanagar",
      "Balangir",
      "Balasore",
      "Bali",
      "Bali",
      "Ballabgarh",
      "Balu",
      "Balurghat",
      "Bambolim",
      "Banda",
      "Bandra",
      "Banga",
      "Bangalore",
      "Bangaon",
      "Bank",
      "Banka",
      "Bankura",
      "Banswara",
      "Bapatla",
      "Barakpur",
      "Baramati",
    ],
  },
  {
    id: 66,
    country: "Indonesia",
    cities: [
      "Abadi",
      "Adiantorop",
      "Airmadidi",
      "Ambarawa",
      "Ambon City",
      "Amlapura",
      "Anggrek",
      "Angkasa",
      "Area",
      "Badung",
      "Badung",
      "Bali",
      "Balige",
      "Balikpapan",
      "Banda Aceh",
      "Bandar",
      "Bandar Lampung",
      "Bandung",
      "Bangkalan",
      "Bangkinang",
      "Bangli",
      "Banjar",
      "Banjarbaru",
      "Banjarmasin",
      "Banjarnegara",
      "Bantaeng",
      "Bantan",
      "Bantul",
      "Banyumas",
      "Banyuwangi",
      "Baratjaya",
      "Batang",
      "Batu",
      "Baturaja",
      "Baubau",
      "Bekasi",
      "Bengkalis",
      "Bengkulu",
      "Bima",
      "Binjai",
      "Bitung",
      "Blitar",
      "Blora",
      "Bogor",
      "Bojonegoro",
      "Bondowoso",
      "Bontang",
      "Boyolali",
      "Bukit Tinggi",
      "Bulukumba",
      "Buntok",
      "Cakrawala",
      "Cempaka",
      "Cengkareng",
      "Ciamis",
      "Cianjur",
      "Cibitung",
      "Cibubur",
      "Cihampelas",
      "Cikarang",
      "Cikini",
      "Cilacap",
      "Cilegon",
      "Cilegon",
      "Cilincing",
      "Cimahi",
      "Cimanggis",
      "Cipinanglatihan",
      "Ciputat",
      "Cirebon",
      "Citeureup",
      "Darmaga",
      "Darussalam",
      "Demak",
      "Denpasar",
      "Depok",
      "Depok Jaya",
      "Dumai",
      "Duren",
      "Duri",
      "Gandul",
      "Garut",
      "Gedung",
      "Gianyar",
      "Gorontalo",
      "Gresik",
      "Guntung",
      "Gunungsitoli",
      "Holis",
      "Indo",
      "Indramayu",
      "Jagakarsa",
      "Jakarta",
      "Jambi City",
      "Jayapura",
      "Jember",
      "Jepara",
      "Jimbaran",
      "Jombang",
      "Kabanjahe",
    ],
  },
  {
    id: 67,
    country: "Iran",
    cities: [
      "`Aliabad",
      "`Aliabad-e Aq Hesar",
      "`Oryan",
      "Abadan",
      "Abol",
      "Ahvaz",
      "Amlash",
      "Amol",
      "Arak",
      "Ardabil",
      "Ardakan",
      "Arnan",
      "Arsanjan",
      "Asadabad",
      "Ashan",
      "Ashna",
      "Ashtian",
      "Astara",
      "Azad",
      "Azadi",
      "Azaran",
      "Babol",
      "Badr",
      "Baft",
      "Baghin",
      "Baharan",
      "Bakhtiari",
      "Bakhtiaruyeh",
      "Baladeh",
      "Banak",
      "Band",
      "Bandar-e Khamir",
      "Bandar-e Mahshahr",
      "Barbun",
      "Bardsir",
      "Baseri Hadi",
      "Bastak",
      "Behbahan",
      "Behdasht",
      "Behjan",
      "Behshahr",
      "Bidak",
      "Birizg",
      "Birjand",
      "Bonab",
      "Borran-e Bala",
      "Bostan",
      "Bukan",
      "Chabahar",
      "Chah Deraz",
      "Chapar",
      "Dadeh",
      "Damavand",
      "Damghan",
      "Darmian",
      "Dezful",
      "Dorud",
      "Emam",
      "Esfarayen",
      "Eslamshahr",
      "Estahban",
      "Evin",
      "Falavarjan",
      "Fardis",
      "Farsi",
      "Fasa",
      "Fordu",
      "Garmsar",
      "Gazan-e Bala",
      "Gerash",
      "Germi",
      "Gharbi",
      "Gilan-e Gharb",
      "Gilas",
      "Golestan",
      "Golpayegan",
      "Golriz",
      "Gorgan",
      "Gostar",
      "Hadishahr",
      "Hamadan",
      "Hasanabad-e Qadamgah",
      "Hashtgerd",
      "Hashtpar",
      "Hirad",
      "Homa",
      "Hormozabad",
      "Hush",
      "Idah",
      "Ilam",
      "Iranshahr",
      "Isfahan",
      "Jadir",
      "Jahan",
      "Jahan Nama",
      "Jahrom",
      "Jiroft",
      "Julfa",
      "Kabir",
      "Kaman",
    ],
  },
  {
    id: 68,
    country: "Iraq",
    cities: [
      "Al `Amarah",
      "Al Hillah",
      "Baghdad",
      "Bahr",
      "Basere",
      "Basra",
      "Erbil",
      "Haji Hasan",
      "Hayat",
      "Karkh",
      "Kirkuk",
      "Manawi",
      "Mosul",
      "Najaf",
      "Sulaymaniyah",
      "Tikrit",
    ],
  },
  {
    id: 69,
    country: "Ireland",
    cities: [
      "Abbeyfeale",
      "Abbeyleix",
      "Ardee",
      "Arklow",
      "Artane",
      "Ashbourne",
      "Athboy",
      "Athenry",
      "Athlone",
      "Athy",
      "Bagenalstown",
      "Bailieborough",
      "Balbriggan",
      "Baldoyle",
      "Balgriffin",
      "Ballina",
      "Ballinadee",
      "Ballinasloe",
      "Ballincollig",
      "Ballineen",
      "Ballinrobe",
      "Ballintober",
      "Ballivor",
      "Ballon",
      "Ballsbridge",
      "Ballybrack",
      "Ballybrit",
      "Ballycullen",
      "Ballyfermot",
      "Ballygarvan",
      "Ballyhooly",
      "Ballymahon",
      "Ballymote",
      "Ballymount",
      "Ballymun",
      "Ballyphilip",
      "Ballyragget",
      "Ballyroe",
      "Ballyvaghan",
      "Bandon",
      "Bantry",
      "Berrings",
      "Bettystown",
      "Birr",
      "Blackrock",
      "Blanchardstown",
      "Blessington",
      "Bodyke",
      "Boherbue",
      "Bray",
      "Broadford",
      "Buncrana",
      "Bundoran",
      "Cabinteely",
      "Cabra",
      "Caher",
      "Cahersiveen",
      "Callan",
      "Carbury",
      "Carlow",
      "Carnew",
      "Carraroe",
      "Carrick",
      "Carrick on Shannon",
      "Carrick-on-Suir",
      "Carrickmacross",
      "Carrickmines",
      "Carrigaline",
      "Carrigtohill",
      "Cashel",
      "Castlebar",
      "Castleblayney",
      "Castlebridge",
      "Castleknock",
      "Castlemaine",
      "Castlerea",
      "Cavan",
      "Celbridge",
      "Clane",
      "Clarecastle",
      "Claregalway",
      "Claremorris",
      "Clogherhead",
      "Clonakilty",
      "Clondalkin",
      "Clonee",
      "Clones",
      "Clonmel",
      "Clonsilla",
      "Clontarf",
      "Coachford",
      "Cobh",
      "Coolock",
      "Cork",
      "County Galway",
      "County Wexford",
      "Courtown",
      "Crookhaven",
      "Cross",
      "Crosshaven",
    ],
  },
  {
    id: 70,
    country: "Isle of Man",
    cities: [
      "Ballasalla",
      "Castletown",
      "Crosby",
      "Dalby",
      "Douglas",
      "Foxdale",
      "Laxey",
      "Onchan",
      "Peel",
      "Port Erin",
      "Port Saint Mary",
      "Ramsey",
      "Saint Johns",
    ],
  },
  {
    id: 71,
    country: "Israel",
    cities: [
      "`Alma",
      "`Amir",
      "`Arugot",
      "`Aseret",
      "`En Ayyala",
      "`En HaShelosha",
      "`Evron",
      "Acre",
      "Afiqim",
      "Ahituv",
      "Allonim",
      "Ashdod",
      "Ashqelon",
      "Azor",
      "Bahan",
      "Baraq",
      "Bareqet",
      "Bat Hadar",
      "Bat Hefer",
      "Bat Yam",
      "Beersheba",
      "Ben Shemen-Kefar Hano`ar",
      "Bene Ziyyon",
      "Bet Alfa",
      "Bet Dagan",
      "Bet Oren",
      "Bet Shemesh",
      "Binyamina",
      "Biriyya",
      "Dabburiya",
      "Dimona",
      "Eilat",
      "Elyakhin",
      "Elyaqim",
      "Emunim",
      "Et Taiyiba",
      "Even Yehuda",
      "Gan Hayyim",
      "Gan Yavne",
      "Ganne Tiqwa",
      "Gedera",
      "Gibbeton",
      "Gimzo",
      "Ginnosar",
      "Giv`at Hayyim",
      "Hadar `Am",
      "Hadar Ramatayim",
      "Hadera",
      "Hadid",
      "Haifa",
      "HaKarmel",
      "Haluz",
      "Hazav",
      "Hazor Ashdod",
      "Hazor HaGelilit",
      "Herut",
      "Herzliya",
      "Hever",
      "Hod HaSharon",
      "Holon",
      "Hurfeish",
      "Jaffa",
      "Jerusalem",
      "Kadima",
      "Karkur",
      "Kefar Daniyyel",
      "Kefar Netter",
      "Kefar Witqin",
      "Kefar Yona",
      "Kfar Saba",
      "Liman",
      "Lod",
      "maalot Tarshiha",
      "Magen",
      "Maghar",
      "Mazkeret Batya",
      "Mazliah",
      "Mazor",
      "Mesillat Ziyyon",
      "Migdal",
      "Mikhmoret",
      "Misgav Regional Council",
      "Mizpe Netofa",
      "Modiin",
      "Moran",
      "Naham",
      "Nahariya",
      "Nazareth",
      "Nazerat `Illit",
      "Nesher",
      "Ness Ziona",
      "Netanya",
      "Netivot",
      "Newe Efrayim",
      "Newe Yamin",
      "Nir Zevi",
      "Nirim",
      "Nordiyya",
      "Ofaqim",
      "Or `Aqiva",
    ],
  },
  {
    id: 72,
    country: "Italy",
    cities: [
      "Abano Terme",
      "Abbadia Lariana",
      "Abbadia San Salvatore",
      "Abbasanta",
      "Abbiategrasso",
      "Abetone",
      "Acate",
      "Acerno",
      "Acerra",
      "Aci Castello",
      "Aci Catena",
      "Acireale",
      "Acquafredda",
      "Acquafredda Inferiore",
      "Acquapendente",
      "Acquappesa",
      "Acquaro",
      "Acquasparta",
      "Acquaviva",
      "Acquaviva delle Fonti",
      "Acquaviva Picena",
      "Acqui Terme",
      "Acri",
      "Adelfia",
      "Adrano",
      "Adria",
      "Adro",
      "Affi",
      "Afragola",
      "Africo Nuovo",
      "Agazzano",
      "Agerola",
      "Agira",
      "Agliana",
      "Agliano",
      "Aglientu",
      "Agna",
      "Agnadello",
      "Agnone",
      "Agordo",
      "Agrano",
      "Agrate Brianza",
      "Agrigento",
      "Agro",
      "Agropoli",
      "Agugliano",
      "Agugliaro",
      "Ai Palazzi",
      "Aiello",
      "Aiello del Sabato",
      "Ailano",
      "Ailoche",
      "Airasca",
      "Airola",
      "Airole",
      "Airuno",
      "Ala",
      "Ala di Stura",
      "Alanno",
      "Alassio",
      "Alatri",
      "Alba",
      "Albanella",
      "Albano di Lucania",
      "Albano Laziale",
      "Albano Vercellese",
      "Albaredo",
      "Albareto",
      "Albenga",
      "Albergo",
      "Alberobello",
      "Alberoni",
      "Albettone",
      "Albiate",
      "Albignasego",
      "Albina",
      "Albinea",
      "Albino",
      "Albissola Marina",
      "Albizzate",
      "Albuzzano",
      "Alcamo",
      "Alcara li Fusi",
      "Aldeno",
      "Ales",
      "Alessandria",
      "Alessandria della Rocca",
      "Alessano",
      "Alezio",
      "Alfonsine",
      "Alghero",
      "Algund",
      "Alice Castello",
      "Alife",
      "Alimena",
      "Alleghe",
      "Allerona",
      "Alliste",
      "Allumiere",
      "Almenno San Bartolomeo",
    ],
  },
  {
    id: 73,
    country: "Jamaica",
    cities: [
      "Black River",
      "Browns Town",
      "Gordon Town",
      "Gregory Park",
      "Kingston",
      "Mandeville",
      "May Pen",
      "Moneague",
      "Montego Bay",
      "Negril",
      "Ocho Rios",
      "Old Harbour",
      "Port Maria",
      "Portland Cottage",
      "Portmore",
      "Runaway Bay",
      "Spanish Town",
    ],
  },
  {
    id: 74,
    country: "Japan",
    cities: [
      "Abashiri",
      "Abiko",
      "Abira",
      "Aboshiku-okinohama",
      "Agano",
      "Agena",
      "Ageo",
      "Aikawa",
      "Aioi",
      "Aisai",
      "Aitsu",
      "Aizu-Wakamatsu",
      "Akao",
      "Akasaka",
      "Akasaka",
      "Akasaki",
      "Akashi",
      "Akashi",
      "Akeno",
      "Aki",
      "Akiruno-shi",
      "Akishima",
      "Akita",
      "Ama-higashimachi",
      "Amagasaki",
      "Ami",
      "Anabuki",
      "Anan",
      "Anesaki",
      "Anjo",
      "Annaka",
      "Aoicho",
      "Aomori",
      "Arai",
      "Arakawa",
      "Ariake",
      "Arida",
      "Arita",
      "Asahi",
      "Asahi",
      "Asahikawa",
      "Asahimachi",
      "Asaka",
      "Ashihara",
      "Ashikaga",
      "Ashiya",
      "Aso",
      "Atami",
      "Atsugi",
      "Awara",
      "Ayase",
      "Azuchi",
      "Azumino",
      "Bakurocho",
      "Bakurocho",
      "Bandaicho",
      "Bando",
      "Beppu",
      "Bibai",
      "Budo",
      "Chatan",
      "Chiba",
      "Chichibu",
      "Chigasaki",
      "Chiji",
      "Chikusei",
      "Chino",
      "Chiran",
      "Chiryu",
      "Chita",
      "Chitose",
      "Choshi",
      "Chuo",
      "Daido",
      "Daigo",
      "Daimon",
      "Daisen",
      "Daitocho",
      "Date",
      "Ebetsu",
      "Ebina",
      "Ebisu",
      "Echizen",
      "Echizen",
      "Edagawa",
      "Edogawa-ku",
      "Ena",
      "Eniwa-shi",
      "Esashi",
      "Fuchu-machi",
      "Fuchucho",
      "Fuefuki-shi",
      "Fuji",
      "Fujieda",
      "Fujiidera",
      "Fujimi",
      "Fujimino",
      "Fujinomiya",
      "Fujioka",
      "Fujisato",
    ],
  },
  {
    id: 75,
    country: "Kazakhstan",
    cities: [
      "Aksay",
      "Aksoran",
      "Almaty",
      "Aqtas",
      "Aqtau",
      "Astana",
      "Atyrau",
      "Baikonur",
      "Dostyk",
      "Dzhezkazgan",
      "Ekibastuz",
      "Esil",
      "Karagandy",
      "Karagandy",
      "Kazakh",
      "Kentau",
      "Koktem",
      "Kostanay",
      "Kyzyl",
      "Kyzylorda",
      "Lomonosovka",
      "Oral",
      "Pavlodar",
      "Petropavl",
      "Qaraghandy",
      "Qaskeleng",
      "Ridder",
      "Rudnyy",
      "Semey",
      "Serebryansk",
      "Shymkent",
      "Sonaly",
      "Stepnogorsk",
      "Taldyk",
      "Taldykorgan",
      "Talghar",
      "Taraz",
      "Temirtau",
      "Turkestan",
      "Uritskiy",
      "Ust-Kamenogorsk",
      "Vostok",
      "Zyryanovsk",
    ],
  },
  {
    id: 76,
    country: "Kenya",
    cities: [
      "Bondo",
      "Chuka",
      "Eldoret",
      "Kabete",
      "Kaiboi",
      "Karatina",
      "Kiambu",
      "Kikuyu",
      "Kisii",
      "Kisumu",
      "Kitale",
      "Kitui",
      "Machakos",
      "Maseno",
      "Mbita",
      "Mombasa",
      "Nairobi",
      "Nakuru",
      "Sawa Sawa",
      "Siaya",
      "Thika",
      "Turbo",
      "Wote",
    ],
  },
  {
    id: 77,
    country: "Kosovo",
    cities: ["Dunavo", "Ferizaj", "Mitrovica", "Pristina", "Prizren"],
  },
  {
    id: 78,
    country: "Kuwait",
    cities: [
      "Abraq Khaytan",
      "Ad Dasmah",
      "Ad Dawhah",
      "Al Ahmadi",
      "Al Farwaniyah",
      "Al Shamiya",
      "Ar Rawdah",
      "As Salimiyah",
      "Ash Shu`aybah",
      "Ash Shuwaykh",
      "Bayan",
      "Hawalli",
      "Janub as Surrah",
      "Kayfan",
      "Kuwait City",
      "Salwa",
    ],
  },
  {
    id: 79,
    country: "Latvia",
    cities: [
      "Adazi",
      "Agenskalns",
      "Aizkraukle",
      "Aizpute",
      "Baldone",
      "Balvi",
      "Bauska",
      "Brankas",
      "Carnikava",
      "Centrs",
      "Daugavpils",
      "Dobele",
      "Durbe",
      "Gulbene",
      "Ilguciems",
      "Izvalta",
      "Jaunolaine",
      "Jelgava",
      "Kandava",
      "Kolka",
      "Lapmezciems",
      "Liepa",
      "Ludza",
      "Madona",
      "Malpils",
      "Malta",
      "Marupe",
      "Mazsalaca",
      "Ogre",
      "Olaine",
      "Ozolnieki",
      "Pilsrundale",
      "Priedkalne",
      "Pure",
      "Riga",
      "Salaspils",
      "Saldus",
      "Sigulda",
      "Smiltene",
      "Stalgene",
      "Talsi",
      "Tukums",
      "Valka",
      "Valmiera",
      "Varsava",
      "Ventspils",
      "Zasa",
      "Zilupe",
    ],
  },
  {
    id: 80,
    country: "Lebanon",
    cities: [
      "Aaley",
      "Adma",
      "Ashrafiye",
      "Baabda",
      "Baalbek",
      "Beirut",
      "Broummana",
      "Bsalim",
      "Chekka",
      "Dbaiye",
      "Dik el Mehdi",
      "Halba",
      "Hboub",
      "Sarba",
      "Sidon",
      "Tripoli",
      "Yanar",
      "Zgharta",
    ],
  },
  {
    id: 81,
    country: "Libya",
    cities: ["Benghazi", "Misratah", "Sabha", "Tripoli", "Zliten"],
  },
  {
    id: 82,
    country: "Liechtenstein",
    cities: [
      "Balzers",
      "Bendern",
      "Eschen",
      "Gamprin",
      "Mauren",
      "Nendeln",
      "Planken",
      "Ruggell",
      "Schaan",
      "Schaanwald",
      "Schellenberg",
      "Triesen",
      "Triesenberg",
      "Vaduz",
    ],
  },
  {
    id: 83,
    country: "Luxembourg",
    cities: [
      "Ahn",
      "Alzingen",
      "Bascharage",
      "Beaufort",
      "Beckerich",
      "Beggen",
      "Beidweiler",
      "Belvaux",
      "Berchem",
      "Bereldange",
      "Bergem",
      "Bertrange",
      "Bettembourg",
      "Betzdorf",
      "Bigonville",
      "Bissen",
      "Bivange",
      "Bofferdange",
      "Bonnevoie",
      "Bourglinster",
      "Bridel",
      "Burmerange",
      "Canach",
      "Cap",
      "Capellen",
      "Colmar",
      "Contern",
      "Crauthem",
      "Dalheim",
      "Differdange",
      "Dippach",
      "Dudelange",
      "Echternach",
      "Ehnen",
      "Ernster",
      "Erpeldange-lez-Bous",
      "Esch-sur-Alzette",
      "Esch-sur-Sure",
      "Ettelbruck",
      "Foetz",
      "Frisange",
      "Godbrange",
      "Goetzingen",
      "Gonderange",
      "Gosseldange",
      "Gostingen",
      "Grevenknapp",
      "Grevenmacher",
      "Grosbous",
      "Hagen",
      "Hautcharage",
      "Heffingen",
      "Heisdorf-sur-Alzette",
      "Helmdange",
      "Helmsange",
      "Hersberg",
      "Hesperange",
      "Hobscheid",
      "Hollerich",
      "Holzem",
      "Huncherange",
      "Hunsdorf",
      "Itzig",
      "Junglinster",
      "Kayl",
      "Kehlen",
      "Kleinbettingen",
      "Koetschette",
      "Lamadelaine",
      "Larochette",
      "Leudelange",
      "Limpertsberg",
      "Lintgen",
      "Lorentzweiler",
      "Luxembourg",
      "Luxembourg-Kirchberg",
      "Mamer",
      "Medernach",
      "Merl",
      "Mersch",
      "Mertert",
      "Mondercange",
      "Mondorf-les-Bains",
      "Moutfort",
      "Niedercorn",
      "Noerdange",
      "Nospelt",
      "Oberanven",
      "Oetrange",
      "Olm",
      "Pontpierre",
      "Remerschen",
      "Remich",
      "Rodange",
      "Roeser",
      "Roodt-sur-Syre",
      "Rumelange",
      "Sandweiler",
      "Sanem",
      "Schieren",
    ],
  },
  {
    id: 84,
    country: "Macedonia",
    cities: [
      "Berovo",
      "Bitola",
      "Bogdanci",
      "Cair",
      "Debar",
      "Delcevo",
      "Demir Hisar",
      "Gevgelija",
      "Gostivar",
      "Ilinden",
      "Kadino",
      "Kavadarci",
      "Kicevo",
      "Kumanovo",
      "Labunista",
      "Lisice",
      "Makedonska Kamenica",
      "Negotino",
      "Novo Selo",
      "Ohrid",
      "Prilep",
      "Pripor",
      "Probistip",
      "Radovis",
      "Shtip",
      "Skopje",
      "Struga",
      "Strumica",
      "Tetovo",
      "Veles",
    ],
  },
  {
    id: 85,
    country: "Madagascar",
    cities: [
      "Ambanja",
      "Antananarivo",
      "Antsirabe",
      "Antsiranana",
      "Fianarantsoa",
      "Toamasina",
      "Toliara",
    ],
  },
  {
    id: 86,
    country: "Malaysia",
    cities: [
      "Alor Gajah",
      "Alor Star",
      "Ampang",
      "Ayer Itam",
      "Ayer Tawar",
      "Bachok",
      "Bagan Serai",
      "Bahau",
      "Balik Pulau",
      "Bandar",
      "Bandar Baru Bangi",
      "Bandar Tenggara",
      "Bandar Tun Razak",
      "Bangi",
      "Banting",
      "Baru",
      "Batang Berjuntai",
      "Batang Kali",
      "Batu",
      "Batu Arang",
      "Batu Berendam",
      "Batu Caves",
      "Batu Feringgi",
      "Batu Gajah",
      "Batu Pahat",
      "Bau",
      "Bayan Lepas",
      "Beaufort",
      "Bedong",
      "Bentung",
      "Benut",
      "Bidur",
      "Bintulu",
      "Bongawan",
      "Broga",
      "Bukit Asahan",
      "Bukit Gambir",
      "Bukit Kayu Hitam",
      "Bukit Mertajam",
      "Bukit Pasir",
      "Bukit Rotan",
      "Butterworth",
      "Cameron Highlands",
      "Changloon",
      "Chemor",
      "Cheras",
      "Cukai",
      "Cyberjaya",
      "Damansara",
      "Dengkil",
      "Dungun",
      "Durian Tunggal",
      "Gebeng",
      "Gelang Patah",
      "Gemas",
      "Genting",
      "George Town",
      "Gerik",
      "Gopeng",
      "Gua Musang",
      "Gurun",
      "Hulu Langat",
      "Hutan Melintang",
      "Inanam",
      "Ipoh",
      "Itam",
      "Jasin",
      "Jawi",
      "Jelutong",
      "Jenjarum",
      "Jeram",
      "Jerantut",
      "Jertih",
      "Jinjang",
      "Jitra",
      "Johor Bahru",
      "Juasseh",
      "Kajang",
      "Kampar",
      "Kampong Changkat",
      "Kampong Kahang Batu Twenty-eight",
      "Kampong Kemaman",
      "Kampong Pasir Segambut",
      "Kampung Ayer Keroh",
      "Kampung Baharu Nilai",
      "Kampung Batu Kikir",
      "Kampung Batu Uban",
      "Kampung Bota Kiri",
      "Kampung Likas",
      "Kampung Paya Simpang Empat Genting",
      "Kampung Pekan Kechil Beranang",
      "Kampung Tanjung Aru",
      "Kampung Tasek",
      "Kampung Teluk Baru",
      "Kampung Teriang",
      "Kamunting",
      "Kangar",
      "Kapar",
      "Karak",
      "Keningau",
    ],
  },
  {
    id: 87,
    country: "Malta",
    cities: [
      "Attard",
      "Balzan",
      "Bingemma",
      "Birgu",
      "Birkirkara",
      "Bugibba",
      "Cospicua",
      "Dingli",
      "Fgura",
      "Floriana",
      "Fontana",
      "Ghajnsielem",
      "Gharb",
      "Ghasri",
      "Ghaxaq",
      "Gudja",
      "Gzira",
      "Hal Gharghur",
      "Hamrun",
      "Haz-Zebbug",
      "Il-Madliena",
      "Il-Pergla",
      "Imsida",
      "Imtarfa",
      "Iz-Zebbiegh",
      "Kirkop",
      "L-Iklin",
      "L-Iskorvit",
      "Lija",
      "Luqa",
      "Manikata",
      "Marsa",
      "Marsalforn",
      "Marsaskala",
      "Marsaxlokk",
      "Mdina",
      "Mellieha",
      "Mosta",
      "Mqabba",
      "Munxar",
      "Nadur",
      "Naxxar",
      "Paola",
      "Pembroke",
      "Qormi",
      "Qrendi",
      "Rabat",
      "Safi",
      "Saint John",
      "Saint Lawrence",
      "Saint Lucia",
      "Saint Venera",
      "San Pawl il-Bahar",
      "Sannat",
      "Senglea",
      "Siggiewi",
      "Sliema",
      "Swieqi",
      "Tarxien",
      "Valletta",
      "Victoria",
      "Xaghra",
      "Xewkija",
      "Zabbar",
      "Zejtun",
      "Zurrieq",
    ],
  },
  {
    id: 88,
    country: "Martinique",
    cities: [
      "Case-Pilote",
      "Ducos",
      "Fort-de-France",
      "Le Carbet",
      "Le Diamant",
      "Le Francois",
      "Le Gros-Morne",
      "Le Lamentin",
      "Le Morne-Rouge",
      "Le Robert",
      "Les Trois-Ilets",
      "Riviere-Salee",
      "Saint-Esprit",
      "Saint-Joseph",
      "Sainte-Anne",
      "Sainte-Luce",
      "Sainte-Marie",
      "Schoelcher",
    ],
  },
  {
    id: 89,
    country: "Mauritius",
    cities: [
      "Beau Bassin",
      "Chemin Grenier",
      "Ebene CyberCity",
      "Floreal",
      "Goodlands",
      "Le Reduit",
      "Port Louis",
      "Port Mathurin",
      "Quatre Bornes",
      "Rose Hill",
      "Saint Jean",
      "Tamarin",
      "Vacoas",
    ],
  },
  {
    id: 90,
    country: "Mayotte",
    cities: [
      "Bandaboa",
      "Chiconi",
      "Combani",
      "Dzaoudzi",
      "Dzoumonye",
      "Koungou",
      "Mamoudzou",
      "Ouangani",
      "Pamandzi",
      "Sada",
      "Tsingoni",
      "Tsoundzou 1",
    ],
  },
  {
    id: 91,
    country: "Mexico",
    cities: [
      "Abasolo",
      "Acambaro",
      "Acambay",
      "Acapulco",
      "Acatic",
      "Acatlan de Perez Figueroa",
      "Acatzingo de Hidalgo",
      "Acolman",
      "Actopan",
      "Acuna",
      "Adolfo Lopez Mateos",
      "Adolfo Ruiz Cortines",
      "Agua Amarga",
      "Agua Azul",
      "Agua Dulce",
      "Agua Prieta",
      "Aguascalientes",
      "Ahome",
      "Ahualulco de Mercado",
      "Ajijic",
      "Alamo",
      "Alamos",
      "Aldama",
      "Allende",
      "Almada",
      "Almoloya",
      "Altamira",
      "Altotonga",
      "Alvaro Obregon Borough",
      "Amado Nervo",
      "Ameca",
      "Amecameca de Juarez",
      "Anahuac",
      "Anahuac",
      "Angamacutiro de la Union",
      "Apan",
      "Apaseo el Alto",
      "Apaseo el Grande",
      "Apatzingan",
      "Apaxco de Ocampo",
      "Apizaco",
      "Apodaca",
      "Arandas",
      "Arcelia",
      "Arizpe",
      "Arriaga",
      "Asuncion Ixtaltepec",
      "Asuncion Nochixtlan",
      "Atequiza",
      "Atizapan",
      "Atlacholoaya",
      "Atlacomulco",
      "Atlatlahucan",
      "Atlixco",
      "Atlzayanca",
      "Atotonilco el Alto",
      "Atoyac de Alvarez",
      "Autlan de Navarro",
      "Autopista Puebla Orizaba 185 (La Condusa)",
      "Axochiapan",
      "Azcapotzalco",
      "Azteca",
      "Badiraguato",
      "Bahia de Kino",
      "Baja California",
      "Balancan de Dominguez",
      "Bamoa",
      "Banderas del Aguila",
      "Banderilla",
      "Barra de Navidad",
      "Barranca de Santa Clara",
      "Barrio de Mexico",
      "Benito Juarez",
      "Benito Juarez",
      "Benito Juarez",
      "Benito Juarez (Santa Elena)",
      "Berriozabal",
      "Boca del Rio",
      "Brisas Barra de Suchiate",
      "Bucerias",
      "Cabo San Lucas",
      "Cabos",
      "Cadereyta",
      "Cadereyta de Montes",
      "Cadereyta Jimenez",
      "Cajeme",
      "Cajititlan",
      "Camargo",
      "Campeche",
      "Campestre Tarimbaro",
      "Cananea",
      "Canatlan",
      "Candelaria",
      "Cardenas",
      "Cardonal",
      "Catemaco",
      "Cazones de Herrera",
      "Celaya",
      "Centro",
      "Centro",
    ],
  },
  {
    id: 92,
    country: "Mongolia",
    cities: [
      "Altai",
      "Arvayheer",
      "Baruun-Urt",
      "Bayangol",
      "Bayanhongor",
      "Cecerleg",
      "Chihertey",
      "Choyr",
      "Dalandzadgad",
      "Darhan",
      "Han-Uul",
      "Javhlant",
      "Khovd",
      "Mandalgovi",
      "Ovoot",
      "Saynshand",
      "Toyrim",
      "Ulaan-Uul",
      "Ulan Bator",
      "Uliastay",
      "Undurkhaan",
    ],
  },
  {
    id: 93,
    country: "Montenegro",
    cities: [
      "Budva",
      "Crna Gora",
      "Herceg Novi",
      "Igalo",
      "Kotor",
      "Niksic",
      "Pljevlja",
      "Podgorica",
      "Stari Bar",
      "Ulcinj",
    ],
  },
  {
    id: 94,
    country: "Morocco",
    cities: [
      "Afourer",
      "Agadir",
      "Ait Melloul",
      "Al Hoceima",
      "Assa",
      "Benguerir",
      "Beni Mellal",
      "Berrechid",
      "Casablanca",
      "Deroua",
      "El Gara",
      "El Hajeb",
      "El Jadida",
      "Erfoud",
      "Fes",
      "Fkih Ben Salah",
      "Kenitra",
      "Khemisset",
      "Khouribga",
      "Ksar el Kebir",
      "Larache",
      "Mansour",
      "Marrakesh",
      "Mehediyah",
      "Meknes",
      "Mohammedia",
      "Nador",
      "Ouazzane",
      "Oued Zem",
      "Oujda",
      "Oulad Teima",
      "Rabat",
      "Safi",
      "Sefrou",
      "Settat",
      "Sidi Bennour",
      "Sidi Slimane",
      "Skhirat",
      "Tahala",
      "Tan-Tan",
      "Tangier",
      "Tarfaya",
      "Taza",
      "Temara",
      "Tiflet",
      "Tiznit",
      "Touissite",
    ],
  },
  {
    id: 95,
    country: "Mozambique",
    cities: [
      "Beira",
      "Maputo",
      "Matola",
      "Mozambique",
      "Nampula",
      "Pemba",
      "Quelimane",
      "Tete",
    ],
  },
  {
    id: 96,
    country: "Myanmar [Burma]",
    cities: ["Hlaing", "Inya", "Kyauktada", "Mandalay", "Wagan", "Yangon"],
  },
  {
    id: 97,
    country: "Namibia",
    cities: [
      "Etunda",
      "Grootfontein",
      "Katima Mulilo",
      "Keetmanshoop",
      "Mpapuka",
      "Olympia",
      "Ondangwa",
      "Ongwediva",
      "Oranjemund",
      "Oshakati",
      "Otjiwarongo",
      "Outapi",
      "Swakopmund",
      "Tsumeb",
      "Walvis Bay",
      "Windhoek",
    ],
  },
  {
    id: 98,
    country: "Nepal",
    cities: [
      "Bharatpur",
      "Jawlakhel",
      "Kathmandu",
      "Lumbini",
      "Palpa",
      "Patan",
    ],
  },
  {
    id: 99,
    country: "Netherlands",
    cities: [
      "Aagtekerke",
      "Aalburg",
      "Aalden",
      "Aalsmeer",
      "Aalsmeerderbrug",
      "Aalst",
      "Aalten",
      "Aardenburg",
      "Abbekerk",
      "Abbenes",
      "Abcoude",
      "Achterberg",
      "Achterveld",
      "Achthuizen",
      "Achtmaal",
      "Aduard",
      "Aerdenhout",
      "Aerdt",
      "Afferden",
      "Akersloot",
      "Akkrum",
      "Albergen",
      "Alblasserdam",
      "Alde Leie",
      "Alem",
      "Alkmaar",
      "Almelo",
      "Almere",
      "Almere Haven",
      "Almkerk",
      "Alphen",
      "Alphen aan den Rijn",
      "Ameide",
      "America",
      "Amerongen",
      "Amersfoort",
      "Ammerstol",
      "Ammerzoden",
      "Amstelhoek",
      "Amstelveen",
      "Amstenrade",
      "Amsterdam",
      "Anderen",
      "Andijk",
      "Ane",
      "Angeren",
      "Anjum",
      "Ankeveen",
      "Anloo",
      "Anna Paulowna",
      "Annen",
      "Apeldoorn",
      "Appelscha",
      "Appeltern",
      "Appingedam",
      "Arcen",
      "Arkel",
      "Arnemuiden",
      "Arnhem",
      "Asperen",
      "Assen",
      "Assendelft",
      "Asten",
      "Augustinusga",
      "Avenhorn",
      "Axel",
      "Baambrugge",
      "Baarland",
      "Baarle-Nassau",
      "Baarlo",
      "Baarn",
      "Baars",
      "Babberich",
      "Badhoevedorp",
      "Baexem",
      "Bakel",
      "Baken",
      "Bakhuizen",
      "Balgoij",
      "Balk",
      "Ballum",
      "Banholt",
      "Barchem",
      "Barendrecht",
      "Barneveld",
      "Batenburg",
      "Bathmen",
      "Bavel",
      "Bedum",
      "Beegden",
      "Beek",
      "Beek",
      "Beek",
      "Beekbergen",
      "Beerta",
      "Beerzerveld",
      "Beesd",
      "Beesel",
      "Beets",
      "Beetsterzwaag",
    ],
  },
  {
    id: 100,
    country: "New Caledonia",
    cities: ["Dumbea", "Mont-Dore", "Noumea", "Nouville", "Paita"],
  },
];
