import { Key } from "react";

export type CountriesData = {
  id: Key;
  country: string;
  cities: string[];
  flag: string;
};

export const countriesData: CountriesData[] = [
  {
    id: 1,
    country: "Afghanistan",
    cities: ["Herat", "Kabul", "Kandahar"],
    flag: "https://flagcdn.com/w320/af.png",
  },
  {
    id: 2,
    country: "Albania",
    cities: ["Elbasan", "Petran", "Pogradec"],
    flag: "https://flagcdn.com/w320/al.png",
  },
  {
    id: 3,
    country: "Algeria",
    cities: ["Algiers", "Oran", "Constantine"],
    flag: "https://flagcdn.com/w320/dz.png",
  },
  {
    id: 4,
    country: "Andorra",
    cities: ["Andorra la Vella", "Escaldes-Engordany", "Andorra la Vella"],
    flag: "https://flagcdn.com/w320/ad.png",
  },
  {
    id: 5,
    country: "Angola",
    cities: ["Luanda", "Ndalatando", "Lubango"],
    flag: "https://flagcdn.com/w320/ao.png",
  },
  {
    id: 6,
    country: "Antigua and Barbuda",
    cities: ["Saint John's", "All Saints", "Liberta"],
    flag: "https://flagcdn.com/w320/ag.png",
  },
  {
    id: 7,
    country: "Argentina",
    cities: ["Buenos Aires", "Cordoba", "Rosario"],
    flag: "https://flagcdn.com/w320/ar.png",
  },
  {
    id: 8,
    country: "Armenia",
    cities: ["Yerevan", "Gyumri", "Vanadzor"],
    flag: "https://flagcdn.com/w320/am.png",
  },
  {
    id: 9,
    country: "Australia",
    cities: ["Sydney", "Melbourne", "Brisbane"],
    flag: "https://flagcdn.com/w320/au.png",
  },
  {
    id: 10,
    country: "Austria",
    cities: ["Vienna", "Salzburg", "Graz"],
    flag: "https://flagcdn.com/w320/at.png",
  },
  {
    id: 11,
    country: "Azerbaijan",
    cities: ["Baku", "Ganja", "Lankaran"],
    flag: "https://flagcdn.com/w320/az.png",
  },
  {
    id: 12,
    country: "Bahamas",
    cities: ["Nassau", "Freeport", "West End"],
    flag: "https://flagcdn.com/w320/bs.png",
  },
  {
    id: 13,
    country: "Bahrain",
    cities: ["Manama", "Muharraq", "Riffa"],
    flag: "https://flagcdn.com/w320/bh.png",
  },
  {
    id: 14,
    country: "Bangladesh",
    cities: ["Dhaka", "Chittagong", "Khulna"],
    flag: "https://flagcdn.com/w320/bd.png",
  },
  {
    id: 15,
    country: "Barbados",
    cities: ["Bridgetown", "Oistins", "Speightstown"],
    flag: "https://flagcdn.com/w320/bb.png",
  },
  {
    id: 16,
    country: "Belarus",
    cities: ["Minsk", "Brest", "Gomel"],
    flag: "https://flagcdn.com/w320/by.png",
  },
  {
    id: 17,
    country: "Belgium",
    cities: ["Brussels", "Antwerp", "Ghent"],
    flag: "https://flagcdn.com/w320/be.png",
  },
  {
    id: 18,
    country: "Belize",
    cities: ["Belmopan", "Belize City", "San Ignacio"],
    flag: "https://flagcdn.com/w320/bz.png",
  },
  {
    id: 19,
    country: "Benin",
    cities: ["Cotonou", "Porto-Novo", "Parakou"],
    flag: "https://flagcdn.com/w320/bj.png",
  },
  {
    id: 20,
    country: "Bhutan",
    cities: ["Thimphu", "Paro", "Phuentsholing"],
    flag: "https://flagcdn.com/w320/bt.png",
  },
  {
    id: 21,
    country: "Bolivia",
    cities: ["La Paz", "Santa Cruz", "Cochabamba"],
    flag: "https://flagcdn.com/w320/bo.png",
  },
  {
    id: 22,
    country: "Bosnia and Herzegovina",
    cities: ["Sarajevo", "Banja Luka", "Tuzla"],
    flag: "https://flagcdn.com/w320/ba.png",
  },
  {
    id: 23,
    country: "Botswana",
    cities: ["Gaborone", "Francistown", "Maun"],
    flag: "https://flagcdn.com/w320/bw.png",
  },
  {
    id: 24,
    country: "Brazil",
    cities: ["Brasília", "São Paulo", "Rio de Janeiro"],
    flag: "https://flagcdn.com/w320/br.png",
  },
  {
    id: 25,
    country: "Brunei",
    cities: ["Bandar Seri Begawan", "Kuala Belait", "Seria"],
    flag: "https://flagcdn.com/w320/bn.png",
  },
  {
    id: 26,
    country: "Bulgaria",
    cities: ["Sofia", "Plovdiv", "Varna"],
    flag: "https://flagcdn.com/w320/bg.png",
  },
  {
    id: 27,
    country: "Burkina Faso",
    cities: ["Ouagadougou", "Bobo-Dioulasso", "Koudougou"],
    flag: "https://flagcdn.com/w320/bf.png",
  },
  {
    id: 28,
    country: "Burundi",
    cities: ["Gitega", "Bujumbura", "Ngozi"],
    flag: "https://flagcdn.com/w320/bi.png",
  },
  {
    id: 29,
    country: "Cabo Verde",
    cities: ["Praia", "Mindelo", "Santa Maria"],
    flag: "https://flagcdn.com/w320/cv.png",
  },
  {
    id: 30,
    country: "Cambodia",
    cities: ["Phnom Penh", "Siem Reap", "Battambang"],
    flag: "https://flagcdn.com/w320/kh.png",
  },
  {
    id: 31,
    country: "Cameroon",
    cities: ["Yaoundé", "Douala", "Bafoussam"],
    flag: "https://flagcdn.com/w320/cm.png",
  },
  {
    id: 32,
    country: "Canada",
    cities: ["Ottawa", "Toronto", "Vancouver"],
    flag: "https://flagcdn.com/w320/ca.png",
  },
  {
    id: 33,
    country: "Central African Republic",
    cities: ["Bangui", "Bangassou", "Berberati"],
    flag: "https://flagcdn.com/w320/cf.png",
  },
  {
    id: 34,
    country: "Chad",
    cities: ["N'Djamena", "Moundou", "Sarh"],
    flag: "https://flagcdn.com/w320/td.png",
  },
  {
    id: 35,
    country: "Chile",
    cities: ["Santiago", "Valparaíso", "Concepción"],
    flag: "https://flagcdn.com/w320/cl.png",
  },
  {
    id: 36,
    country: "China",
    cities: ["Beijing", "Shanghai", "Guangzhou"],
    flag: "https://flagcdn.com/w320/cn.png",
  },
  {
    id: 37,
    country: "Colombia",
    cities: ["Bogotá", "Medellín", "Cali"],
    flag: "https://flagcdn.com/w320/co.png",
  },
  {
    id: 38,
    country: "Comoros",
    cities: ["Moroni", "Mitsamiouli", "Fomboni"],
    flag: "https://flagcdn.com/w320/km.png",
  },
  {
    id: 39,
    country: "Congo, Republic of the",
    cities: ["Brazzaville", "Pointe-Noire", "Dolisie"],
    flag: "https://flagcdn.com/w320/cg.png",
  },
  {
    id: 40,
    country: "Congo, Democratic Republic of the",
    cities: ["Kinshasa", "Lubumbashi", "Goma"],
    flag: "https://flagcdn.com/w320/cd.png",
  },
  {
    id: 41,
    country: "Costa Rica",
    cities: ["San José", "Alajuela", "Cartago"],
    flag: "https://flagcdn.com/w320/cr.png",
  },
  {
    id: 42,
    country: "Croatia",
    cities: ["Zagreb", "Split", "Rijeka"],
    flag: "https://flagcdn.com/w320/hr.png",
  },
  {
    id: 43,
    country: "Cuba",
    cities: ["Havana", "Santiago de Cuba", "Camagüey"],
    flag: "https://flagcdn.com/w320/cu.png",
  },
  {
    id: 44,
    country: "Cyprus",
    cities: ["Nicosia", "Limassol", "Larnaca"],
    flag: "https://flagcdn.com/w320/cy.png",
  },
  {
    id: 45,
    country: "Czech Republic",
    cities: ["Prague", "Brno", "Ostrava"],
    flag: "https://flagcdn.com/w320/cz.png",
  },
  {
    id: 46,
    country: "Denmark",
    cities: ["Copenhagen", "Aarhus", "Odense"],
    flag: "https://flagcdn.com/w320/dk.png",
  },
  {
    id: 47,
    country: "Djibouti",
    cities: ["Djibouti", "Ali Sabieh", "Tadjoura"],
    flag: "https://flagcdn.com/w320/dj.png",
  },
  {
    id: 48,
    country: "Dominica",
    cities: ["Roseau", "Portsmouth", "Marigot"],
    flag: "https://flagcdn.com/w320/dm.png",
  },
  {
    id: 49,
    country: "Dominican Republic",
    cities: ["Santo Domingo", "Santiago", "La Romana"],
    flag: "https://flagcdn.com/w320/do.png",
  },
  {
    id: 50,
    country: "Ecuador",
    cities: ["Quito", "Guayaquil", "Cuenca"],
    flag: "https://flagcdn.com/w320/ec.png",
  },
  {
    id: 51,
    country: "Egypt",
    cities: ["Cairo", "Alexandria", "Giza"],
    flag: "https://flagcdn.com/w320/eg.png",
  },
  {
    id: 52,
    country: "El Salvador",
    cities: ["San Salvador", "Santa Ana", "San Miguel"],
    flag: "https://flagcdn.com/w320/sv.png",
  },
  {
    id: 53,
    country: "Equatorial Guinea",
    cities: ["Malabo", "Bata", "Ebebiyin"],
    flag: "https://flagcdn.com/w320/gq.png",
  },
  {
    id: 54,
    country: "Eritrea",
    cities: ["Asmara", "Keren", "Mendefera"],
    flag: "https://flagcdn.com/w320/er.png",
  },
  {
    id: 55,
    country: "Estonia",
    cities: ["Tallinn", "Tartu", "Narva"],
    flag: "https://flagcdn.com/w320/ee.png",
  },
  {
    id: 56,
    country: "Eswatini",
    cities: ["Mbabane", "Manzini", "Lobamba"],
    flag: "https://flagcdn.com/w320/sz.png",
  },
  {
    id: 57,
    country: "Ethiopia",
    cities: ["Addis Ababa", "Gondar", "Adama"],
    flag: "https://flagcdn.com/w320/et.png",
  },
  {
    id: 58,
    country: "Fiji",
    cities: ["Suva", "Nadi", "Lautoka"],
    flag: "https://flagcdn.com/w320/fj.png",
  },
  {
    id: 59,
    country: "Finland",
    cities: ["Helsinki", "Espoo", "Tampere"],
    flag: "https://flagcdn.com/w320/fi.png",
  },
  {
    id: 60,
    country: "France",
    cities: ["Paris", "Marseille", "Lyon"],
    flag: "https://flagcdn.com/w320/fr.png",
  },
  {
    id: 61,
    country: "Gabon",
    cities: ["Libreville", "Port-Gentil", "Franceville"],
    flag: "https://flagcdn.com/w320/ga.png",
  },
  {
    id: 62,
    country: "Gambia",
    cities: ["Banjul", "Serrekunda", "Brikama"],
    flag: "https://flagcdn.com/w320/gm.png",
  },
  {
    id: 63,
    country: "Georgia",
    cities: ["Tbilisi", "Batumi", "Zugdidi"],
    flag: "https://flagcdn.com/w320/ge.png",
  },
  {
    id: 64,
    country: "Germany",
    cities: ["Berlin", "Munich", "Hamburg"],
    flag: "https://flagcdn.com/w320/de.png",
  },
  {
    id: 65,
    country: "Ghana",
    cities: ["Accra", "Kumasi", "Takoradi"],
    flag: "https://flagcdn.com/w320/gh.png",
  },
  {
    id: 66,
    country: "Greece",
    cities: ["Athens", "Thessaloniki", "Patras"],
    flag: "https://flagcdn.com/w320/gr.png",
  },
  {
    id: 67,
    country: "Grenada",
    cities: ["St. George's", "Grenville", "Gouyave"],
    flag: "https://flagcdn.com/w320/gd.png",
  },
  {
    id: 68,
    country: "Guatemala",
    cities: ["Guatemala City", "Mixco", "Villa Nueva"],
    flag: "https://flagcdn.com/w320/gt.png",
  },
  {
    id: 69,
    country: "Guinea",
    cities: ["Conakry", "Kankan", "Nzérékoré"],
    flag: "https://flagcdn.com/w320/gn.png",
  },
  {
    id: 70,
    country: "Guinea-Bissau",
    cities: ["Bissau", "Bafata", "Gabu"],
    flag: "https://flagcdn.com/w320/gw.png",
  },
  {
    id: 71,
    country: "Guyana",
    cities: ["Georgetown", "New Amsterdam", "Linden"],
    flag: "https://flagcdn.com/w320/gy.png",
  },
  {
    id: 72,
    country: "Haiti",
    cities: ["Port-au-Prince", "Cap-Haïtien", "Jacmel"],
    flag: "https://flagcdn.com/w320/ht.png",
  },
  {
    id: 73,
    country: "Honduras",
    cities: ["Tegucigalpa", "San Pedro Sula", "Choluteca"],
    flag: "https://flagcdn.com/w320/hn.png",
  },
  {
    id: 74,
    country: "Hungary",
    cities: ["Budapest", "Debrecen", "Szeged"],
    flag: "https://flagcdn.com/w320/hu.png",
  },
  {
    id: 75,
    country: "Iceland",
    cities: ["Reykjavík", "Akureyri", "Kopavogur"],
    flag: "https://flagcdn.com/w320/is.png",
  },
  {
    id: 76,
    country: "India",
    cities: ["New Delhi", "Mumbai", "Bengaluru"],
    flag: "https://flagcdn.com/w320/in.png",
  },
  {
    id: 77,
    country: "Indonesia",
    cities: ["Jakarta", "Surabaya", "Bandung"],
    flag: "https://flagcdn.com/w320/id.png",
  },
  {
    id: 78,
    country: "Iran",
    cities: ["Tehran", "Isfahan", "Shiraz"],
    flag: "https://flagcdn.com/w320/ir.png",
  },
  {
    id: 79,
    country: "Iraq",
    cities: ["Baghdad", "Basra", "Erbil"],
    flag: "https://flagcdn.com/w320/iq.png",
  },
  {
    id: 80,
    country: "Ireland",
    cities: ["Dublin", "Cork", "Limerick"],
    flag: "https://flagcdn.com/w320/ie.png",
  },
  {
    id: 81,
    country: "Israel",
    cities: ["Jerusalem", "Tel Aviv", "Haifa"],
    flag: "https://flagcdn.com/w320/il.png",
  },
  {
    id: 82,
    country: "Italy",
    cities: ["Rome", "Milan", "Florence"],
    flag: "https://flagcdn.com/w320/it.png",
  },
  {
    id: 83,
    country: "Jamaica",
    cities: ["Kingston", "Montego Bay", "Spanish Town"],
    flag: "https://flagcdn.com/w320/jm.png",
  },
  {
    id: 84,
    country: "Japan",
    cities: ["Tokyo", "Osaka", "Kyoto"],
    flag: "https://flagcdn.com/w320/jp.png",
  },
  {
    id: 85,
    country: "Jordan",
    cities: ["Amman", "Zarqa", "Irbid"],
    flag: "https://flagcdn.com/w320/jo.png",
  },
  {
    id: 86,
    country: "Kazakhstan",
    cities: ["Almaty", "Nur-Sultan", "Shymkent"],
    flag: "https://flagcdn.com/w320/kz.png",
  },
  {
    id: 87,
    country: "Kenya",
    cities: ["Nairobi", "Mombasa", "Kisumu"],
    flag: "https://flagcdn.com/w320/ke.png",
  },
  {
    id: 88,
    country: "Kiribati",
    cities: ["Tarawa", "Kiritimati", "Banaba"],
    flag: "https://flagcdn.com/w320/ki.png",
  },
  {
    id: 89,
    country: "Kuwait",
    cities: ["Kuwait City", "Jahra", "Ahmadi"],
    flag: "https://flagcdn.com/w320/kw.png",
  },
  {
    id: 90,
    country: "Kyrgyzstan",
    cities: ["Bishkek", "Osh", "Jalal-Abad"],
    flag: "https://flagcdn.com/w320/kg.png",
  },
  {
    id: 91,
    country: "Laos",
    cities: ["Vientiane", "Luang Prabang", "Pakse"],
    flag: "https://flagcdn.com/w320/la.png",
  },
  {
    id: 92,
    country: "Latvia",
    cities: ["Riga", "Daugavpils", "Liepaja"],
    flag: "https://flagcdn.com/w320/lv.png",
  },
  {
    id: 93,
    country: "Lebanon",
    cities: ["Beirut", "Tripoli", "Sidon"],
    flag: "https://flagcdn.com/w320/lb.png",
  },
  {
    id: 94,
    country: "Lesotho",
    cities: ["Maseru", "Maputsoe", "Teyateyaneng"],
    flag: "https://flagcdn.com/w320/ls.png",
  },
  {
    id: 95,
    country: "Liberia",
    cities: ["Monrovia", "Gbarnga", "Buchanan"],
    flag: "https://flagcdn.com/w320/lr.png",
  },
  {
    id: 96,
    country: "Libya",
    cities: ["Tripoli", "Benghazi", "Misrata"],
    flag: "https://flagcdn.com/w320/ly.png",
  },
  {
    id: 97,
    country: "Liechtenstein",
    cities: ["Vaduz", "Schaan", "Eschen"],
    flag: "https://flagcdn.com/w320/li.png",
  },
  {
    id: 98,
    country: "Lithuania",
    cities: ["Vilnius", "Kaunas", "Klaipeda"],
    flag: "https://flagcdn.com/w320/lt.png",
  },
  {
    id: 99,
    country: "Luxembourg",
    cities: ["Luxembourg City", "Esch-sur-Alzette", "Differdange"],
    flag: "https://flagcdn.com/w320/lu.png",
  },
  {
    id: 100,
    country: "Madagascar",
    cities: ["Antananarivo", "Toamasina", "Antsiranana"],
    flag: "https://flagcdn.com/w320/mg.png",
  },
  {
    id: 101,
    country: "Malawi",
    cities: ["Lilongwe", "Blantyre", "Mzuzu"],
    flag: "https://flagcdn.com/w320/mw.png",
  },
  {
    id: 102,
    country: "Malaysia",
    cities: ["Kuala Lumpur", "George Town", "Malacca"],
    flag: "https://flagcdn.com/w320/my.png",
  },
  {
    id: 103,
    country: "Maldives",
    cities: ["Malé", "Fuvahmulah", "Dhidhdhoo"],
    flag: "https://flagcdn.com/w320/mv.png",
  },
  {
    id: 104,
    country: "Mali",
    cities: ["Bamako", "Sikasso", "Kayes"],
    flag: "https://flagcdn.com/w320/ml.png",
  },
  {
    id: 105,
    country: "Malta",
    cities: ["Valletta", "Sliema", "Birkirkara"],
    flag: "https://flagcdn.com/w320/mt.png",
  },
  {
    id: 106,
    country: "Marshall Islands",
    cities: ["Majuro", "Ebeye", "Arno"],
    flag: "https://flagcdn.com/w320/mh.png",
  },
  {
    id: 107,
    country: "Mauritania",
    cities: ["Nouakchott", "Nouadhibou", "Kiffa"],
    flag: "https://flagcdn.com/w320/mr.png",
  },
  {
    id: 108,
    country: "Mauritius",
    cities: ["Port Louis", "Curepipe", "Quatre Bornes"],
    flag: "https://flagcdn.com/w320/mu.png",
  },
  {
    id: 109,
    country: "Mexico",
    cities: ["Mexico City", "Guadalajara", "Monterrey"],
    flag: "https://flagcdn.com/w320/mx.png",
  },
  {
    id: 110,
    country: "Micronesia",
    cities: ["Palikir", "Kolonia", "Yap"],
    flag: "https://flagcdn.com/w320/fm.png",
  },
  {
    id: 111,
    country: "Moldova",
    cities: ["Chisinau", "Bălți", "Bender"],
    flag: "https://flagcdn.com/w320/md.png",
  },
  {
    id: 112,
    country: "Monaco",
    cities: ["Monaco", "Monte Carlo", "La Condamine"],
    flag: "https://flagcdn.com/w320/mc.png",
  },
  {
    id: 113,
    country: "Mongolia",
    cities: ["Ulaanbaatar", "Erdenet", "Darkhan"],
    flag: "https://flagcdn.com/w320/mn.png",
  },
  {
    id: 114,
    country: "Montenegro",
    cities: ["Podgorica", "Nikšić", "Herceg Novi"],
    flag: "https://flagcdn.com/w320/me.png",
  },
  {
    id: 115,
    country: "Morocco",
    cities: ["Rabat", "Casablanca", "Marrakech"],
    flag: "https://flagcdn.com/w320/ma.png",
  },
  {
    id: 116,
    country: "Mozambique",
    cities: ["Maputo", "Beira", "Nampula"],
    flag: "https://flagcdn.com/w320/mz.png",
  },
  {
    id: 117,
    country: "Myanmar",
    cities: ["Naypyidaw", "Yangon", "Mandalay"],
    flag: "https://flagcdn.com/w320/mm.png",
  },
  {
    id: 118,
    country: "Namibia",
    cities: ["Windhoek", "Swakopmund", "Rundu"],
    flag: "https://flagcdn.com/w320/na.png",
  },
  {
    id: 119,
    country: "Nauru",
    cities: ["Yaren", "Aiwo", "Boe"],
    flag: "https://flagcdn.com/w320/nr.png",
  },
  {
    id: 120,
    country: "Nepal",
    cities: ["Kathmandu", "Pokhara", "Biratnagar"],
    flag: "https://flagcdn.com/w320/np.png",
  },
  {
    id: 121,
    country: "Netherlands",
    cities: ["Amsterdam", "Rotterdam", "Utrecht"],
    flag: "https://flagcdn.com/w320/nl.png",
  },
  {
    id: 122,
    country: "New Zealand",
    cities: ["Wellington", "Auckland", "Christchurch"],
    flag: "https://flagcdn.com/w320/nz.png",
  },
  {
    id: 123,
    country: "Nicaragua",
    cities: ["Managua", "León", "Granada"],
    flag: "https://flagcdn.com/w320/ni.png",
  },
];
